/*
 * Macrofold API
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * ConnectionPatch
 */
@JsonPropertyOrder({
  ConnectionPatch.JSON_PROPERTY_NAME,
  ConnectionPatch.JSON_PROPERTY_KIND,
  ConnectionPatch.JSON_PROPERTY_PROVIDER,
  ConnectionPatch.JSON_PROPERTY_URL,
  ConnectionPatch.JSON_PROPERTY_AUTH_METHOD,
  ConnectionPatch.JSON_PROPERTY_SECRET,
  ConnectionPatch.JSON_PROPERTY_SECRET_HEADERS,
  ConnectionPatch.JSON_PROPERTY_PACKAGE,
  ConnectionPatch.JSON_PROPERTY_PACKAGE_VERSION,
  ConnectionPatch.JSON_PROPERTY_ARGS,
  ConnectionPatch.JSON_PROPERTY_SUBJECT_ID,
  ConnectionPatch.JSON_PROPERTY_SECRET_ENV
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConnectionPatch {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  /**
   * Gets or Sets kind
   */
  public enum KindEnum {
    MODEL(String.valueOf("model")),
    
    MCP_REMOTE(String.valueOf("mcp_remote")),
    
    MCP_STDIO(String.valueOf("mcp_stdio")),
    
    COMPOSIO(String.valueOf("composio")),
    
    SEARCH(String.valueOf("search"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private KindEnum kind;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nullable
  private String provider;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private URI url;

  /**
   * Gets or Sets authMethod
   */
  public enum AuthMethodEnum {
    OAUTH(String.valueOf("oauth")),
    
    BEARER(String.valueOf("bearer")),
    
    HEADERS(String.valueOf("headers")),
    
    API_KEY(String.valueOf("api_key")),
    
    NONE(String.valueOf("none"));

    private String value;

    AuthMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthMethodEnum fromValue(String value) {
      for (AuthMethodEnum b : AuthMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_AUTH_METHOD = "auth_method";
  @javax.annotation.Nullable
  private AuthMethodEnum authMethod;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @javax.annotation.Nullable
  private String secret;

  public static final String JSON_PROPERTY_SECRET_HEADERS = "secret_headers";
  @javax.annotation.Nullable
  private Map<String, String> secretHeaders = new HashMap<>();

  public static final String JSON_PROPERTY_PACKAGE = "package";
  @javax.annotation.Nullable
  private String _package;

  public static final String JSON_PROPERTY_PACKAGE_VERSION = "package_version";
  @javax.annotation.Nullable
  private String packageVersion;

  public static final String JSON_PROPERTY_ARGS = "args";
  @javax.annotation.Nullable
  private List<String> args = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBJECT_ID = "subject_id";
  @javax.annotation.Nullable
  private String subjectId;

  public static final String JSON_PROPERTY_SECRET_ENV = "secret_env";
  @javax.annotation.Nullable
  private Map<String, String> secretEnv = new HashMap<>();

  public ConnectionPatch() { 
  }

  public ConnectionPatch name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ConnectionPatch kind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
  }


  public ConnectionPatch provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * For kind search: brave, exa, tavily, parallel, or firecrawl. All support BYOK with auth_method api_key and a write-only secret. Only brave supports managed search with auth_method none. Provider identity cannot be changed after creation.
   * @return provider
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public ConnectionPatch url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }


  public ConnectionPatch authMethod(@javax.annotation.Nullable AuthMethodEnum authMethod) {
    this.authMethod = authMethod;
    return this;
  }

  /**
   * Get authMethod
   * @return authMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AuthMethodEnum getAuthMethod() {
    return authMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthMethod(@javax.annotation.Nullable AuthMethodEnum authMethod) {
    this.authMethod = authMethod;
  }


  public ConnectionPatch secret(@javax.annotation.Nullable String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * Write-only secret; never returned.
   * @return secret
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@javax.annotation.Nullable String secret) {
    this.secret = secret;
  }


  public ConnectionPatch secretHeaders(@javax.annotation.Nullable Map<String, String> secretHeaders) {
    this.secretHeaders = secretHeaders;
    return this;
  }

  public ConnectionPatch putSecretHeadersItem(String key, String secretHeadersItem) {
    if (this.secretHeaders == null) {
      this.secretHeaders = new HashMap<>();
    }
    this.secretHeaders.put(key, secretHeadersItem);
    return this;
  }

  /**
   * Get secretHeaders
   * @return secretHeaders
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getSecretHeaders() {
    return secretHeaders;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecretHeaders(@javax.annotation.Nullable Map<String, String> secretHeaders) {
    this.secretHeaders = secretHeaders;
  }


  public ConnectionPatch _package(@javax.annotation.Nullable String _package) {
    this._package = _package;
    return this;
  }

  /**
   * Get _package
   * @return _package
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPackage() {
    return _package;
  }


  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackage(@javax.annotation.Nullable String _package) {
    this._package = _package;
  }


  public ConnectionPatch packageVersion(@javax.annotation.Nullable String packageVersion) {
    this.packageVersion = packageVersion;
    return this;
  }

  /**
   * Get packageVersion
   * @return packageVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PACKAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPackageVersion() {
    return packageVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_PACKAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackageVersion(@javax.annotation.Nullable String packageVersion) {
    this.packageVersion = packageVersion;
  }


  public ConnectionPatch args(@javax.annotation.Nullable List<String> args) {
    this.args = args;
    return this;
  }

  public ConnectionPatch addArgsItem(String argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<>();
    }
    this.args.add(argsItem);
    return this;
  }

  /**
   * Get args
   * @return args
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getArgs() {
    return args;
  }


  @JsonProperty(value = JSON_PROPERTY_ARGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArgs(@javax.annotation.Nullable List<String> args) {
    this.args = args;
  }


  public ConnectionPatch subjectId(@javax.annotation.Nullable String subjectId) {
    this.subjectId = subjectId;
    return this;
  }

  /**
   * Get subjectId
   * @return subjectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubjectId() {
    return subjectId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectId(@javax.annotation.Nullable String subjectId) {
    this.subjectId = subjectId;
  }


  public ConnectionPatch secretEnv(@javax.annotation.Nullable Map<String, String> secretEnv) {
    this.secretEnv = secretEnv;
    return this;
  }

  public ConnectionPatch putSecretEnvItem(String key, String secretEnvItem) {
    if (this.secretEnv == null) {
      this.secretEnv = new HashMap<>();
    }
    this.secretEnv.put(key, secretEnvItem);
    return this;
  }

  /**
   * Write-only environment secrets for approved stdio package variables. Visible to processes inside your agent sandbox.
   * @return secretEnv
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getSecretEnv() {
    return secretEnv;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecretEnv(@javax.annotation.Nullable Map<String, String> secretEnv) {
    this.secretEnv = secretEnv;
  }


  /**
   * Return true if this ConnectionPatch object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionPatch connectionPatch = (ConnectionPatch) o;
    return Objects.equals(this.name, connectionPatch.name) &&
        Objects.equals(this.kind, connectionPatch.kind) &&
        Objects.equals(this.provider, connectionPatch.provider) &&
        Objects.equals(this.url, connectionPatch.url) &&
        Objects.equals(this.authMethod, connectionPatch.authMethod) &&
        Objects.equals(this.secret, connectionPatch.secret) &&
        Objects.equals(this.secretHeaders, connectionPatch.secretHeaders) &&
        Objects.equals(this._package, connectionPatch._package) &&
        Objects.equals(this.packageVersion, connectionPatch.packageVersion) &&
        Objects.equals(this.args, connectionPatch.args) &&
        Objects.equals(this.subjectId, connectionPatch.subjectId) &&
        Objects.equals(this.secretEnv, connectionPatch.secretEnv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, kind, provider, url, authMethod, secret, secretHeaders, _package, packageVersion, args, subjectId, secretEnv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionPatch {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    authMethod: ").append(toIndentedString(authMethod)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    secretHeaders: ").append(toIndentedString(secretHeaders)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    packageVersion: ").append(toIndentedString(packageVersion)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    secretEnv: ").append(toIndentedString(secretEnv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `auth_method` to the URL query string
    if (getAuthMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauth_method%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthMethod()))));
    }

    // add `secret` to the URL query string
    if (getSecret() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecret()))));
    }

    // add `secret_headers` to the URL query string
    if (getSecretHeaders() != null) {
      for (String _key : getSecretHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssecret_headers%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getSecretHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getSecretHeaders().get(_key)))));
      }
    }

    // add `package` to the URL query string
    if (getPackage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spackage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPackage()))));
    }

    // add `package_version` to the URL query string
    if (getPackageVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spackage_version%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPackageVersion()))));
    }

    // add `args` to the URL query string
    if (getArgs() != null) {
      for (int i = 0; i < getArgs().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sargs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getArgs().get(i)))));
      }
    }

    // add `subject_id` to the URL query string
    if (getSubjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubjectId()))));
    }

    // add `secret_env` to the URL query string
    if (getSecretEnv() != null) {
      for (String _key : getSecretEnv().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssecret_env%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getSecretEnv().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getSecretEnv().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

