/*
 * Macrofold API
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.macrofold.model.ConnectionCapability;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * Prepare an embedded app connection with no access. Configure an enabled connector and reviewed capability presets on the trusted backend. The customer selects a preset during consent; no Macrofold login is required.
 */
@JsonPropertyOrder({
  CustomerAgentConnectionCreate.JSON_PROPERTY_NAME,
  CustomerAgentConnectionCreate.JSON_PROPERTY_PROVIDER,
  CustomerAgentConnectionCreate.JSON_PROPERTY_CAPABILITIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CustomerAgentConnectionCreate {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nonnull
  private String provider;

  public static final String JSON_PROPERTY_CAPABILITIES = "capabilities";
  @javax.annotation.Nonnull
  private List<ConnectionCapability> capabilities = new ArrayList<>();

  public CustomerAgentConnectionCreate() { 
  }

  public CustomerAgentConnectionCreate name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CustomerAgentConnectionCreate provider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
  }


  public CustomerAgentConnectionCreate capabilities(@javax.annotation.Nonnull List<ConnectionCapability> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public CustomerAgentConnectionCreate addCapabilitiesItem(ConnectionCapability capabilitiesItem) {
    if (this.capabilities == null) {
      this.capabilities = new ArrayList<>();
    }
    this.capabilities.add(capabilitiesItem);
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CAPABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ConnectionCapability> getCapabilities() {
    return capabilities;
  }


  @JsonProperty(value = JSON_PROPERTY_CAPABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapabilities(@javax.annotation.Nonnull List<ConnectionCapability> capabilities) {
    this.capabilities = capabilities;
  }


  /**
   * Return true if this CustomerAgentConnectionCreate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAgentConnectionCreate customerAgentConnectionCreate = (CustomerAgentConnectionCreate) o;
    return Objects.equals(this.name, customerAgentConnectionCreate.name) &&
        Objects.equals(this.provider, customerAgentConnectionCreate.provider) &&
        Objects.equals(this.capabilities, customerAgentConnectionCreate.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, provider, capabilities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAgentConnectionCreate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `capabilities` to the URL query string
    if (getCapabilities() != null) {
      for (int i = 0; i < getCapabilities().size(); i++) {
        if (getCapabilities().get(i) != null) {
          joiner.add(getCapabilities().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scapabilities%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

