/*
 * Macrofold API
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.macrofold.model.DecisionQuestionOneOf;
import dev.macrofold.model.DecisionQuestionOneOf1;
import dev.macrofold.model.DecisionQuestionOneOf2;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import dev.macrofold.ApiClient;
import dev.macrofold.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
@JsonDeserialize(using = DecisionQuestion.DecisionQuestionDeserializer.class)
@JsonSerialize(using = DecisionQuestion.DecisionQuestionSerializer.class)
public class DecisionQuestion extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DecisionQuestion.class.getName());

    public static class DecisionQuestionSerializer extends StdSerializer<DecisionQuestion> {
        public DecisionQuestionSerializer(Class<DecisionQuestion> t) {
            super(t);
        }

        public DecisionQuestionSerializer() {
            this(null);
        }

        @Override
        public void serialize(DecisionQuestion value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class DecisionQuestionDeserializer extends StdDeserializer<DecisionQuestion> {
        public DecisionQuestionDeserializer() {
            this(DecisionQuestion.class);
        }

        public DecisionQuestionDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public DecisionQuestion deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize DecisionQuestionOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DecisionQuestionOneOf.class.equals(Integer.class) || DecisionQuestionOneOf.class.equals(Long.class) || DecisionQuestionOneOf.class.equals(Float.class) || DecisionQuestionOneOf.class.equals(Double.class) || DecisionQuestionOneOf.class.equals(Boolean.class) || DecisionQuestionOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DecisionQuestionOneOf.class.equals(Integer.class) || DecisionQuestionOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DecisionQuestionOneOf.class.equals(Float.class) || DecisionQuestionOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DecisionQuestionOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DecisionQuestionOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DecisionQuestionOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DecisionQuestionOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DecisionQuestionOneOf'", e);
            }

            // deserialize DecisionQuestionOneOf1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DecisionQuestionOneOf1.class.equals(Integer.class) || DecisionQuestionOneOf1.class.equals(Long.class) || DecisionQuestionOneOf1.class.equals(Float.class) || DecisionQuestionOneOf1.class.equals(Double.class) || DecisionQuestionOneOf1.class.equals(Boolean.class) || DecisionQuestionOneOf1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DecisionQuestionOneOf1.class.equals(Integer.class) || DecisionQuestionOneOf1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DecisionQuestionOneOf1.class.equals(Float.class) || DecisionQuestionOneOf1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DecisionQuestionOneOf1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DecisionQuestionOneOf1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DecisionQuestionOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DecisionQuestionOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DecisionQuestionOneOf1'", e);
            }

            // deserialize DecisionQuestionOneOf2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DecisionQuestionOneOf2.class.equals(Integer.class) || DecisionQuestionOneOf2.class.equals(Long.class) || DecisionQuestionOneOf2.class.equals(Float.class) || DecisionQuestionOneOf2.class.equals(Double.class) || DecisionQuestionOneOf2.class.equals(Boolean.class) || DecisionQuestionOneOf2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DecisionQuestionOneOf2.class.equals(Integer.class) || DecisionQuestionOneOf2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DecisionQuestionOneOf2.class.equals(Float.class) || DecisionQuestionOneOf2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DecisionQuestionOneOf2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DecisionQuestionOneOf2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DecisionQuestionOneOf2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DecisionQuestionOneOf2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DecisionQuestionOneOf2'", e);
            }

            if (match == 1) {
                DecisionQuestion ret = new DecisionQuestion();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for DecisionQuestion: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public DecisionQuestion getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "DecisionQuestion cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public DecisionQuestion() {
        super("oneOf", Boolean.FALSE);
    }

    public DecisionQuestion(DecisionQuestionOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public DecisionQuestion(DecisionQuestionOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public DecisionQuestion(DecisionQuestionOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DecisionQuestionOneOf", DecisionQuestionOneOf.class);
        schemas.put("DecisionQuestionOneOf1", DecisionQuestionOneOf1.class);
        schemas.put("DecisionQuestionOneOf2", DecisionQuestionOneOf2.class);
        JSON.registerDescendants(DecisionQuestion.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DecisionQuestion.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DecisionQuestionOneOf, DecisionQuestionOneOf1, DecisionQuestionOneOf2
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(DecisionQuestionOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DecisionQuestionOneOf1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DecisionQuestionOneOf2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DecisionQuestionOneOf, DecisionQuestionOneOf1, DecisionQuestionOneOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * DecisionQuestionOneOf, DecisionQuestionOneOf1, DecisionQuestionOneOf2
     *
     * @return The actual instance (DecisionQuestionOneOf, DecisionQuestionOneOf1, DecisionQuestionOneOf2)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DecisionQuestionOneOf`. If the actual instance is not `DecisionQuestionOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DecisionQuestionOneOf`
     * @throws ClassCastException if the instance is not `DecisionQuestionOneOf`
     */
    public DecisionQuestionOneOf getDecisionQuestionOneOf() throws ClassCastException {
        return (DecisionQuestionOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DecisionQuestionOneOf1`. If the actual instance is not `DecisionQuestionOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DecisionQuestionOneOf1`
     * @throws ClassCastException if the instance is not `DecisionQuestionOneOf1`
     */
    public DecisionQuestionOneOf1 getDecisionQuestionOneOf1() throws ClassCastException {
        return (DecisionQuestionOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DecisionQuestionOneOf2`. If the actual instance is not `DecisionQuestionOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DecisionQuestionOneOf2`
     * @throws ClassCastException if the instance is not `DecisionQuestionOneOf2`
     */
    public DecisionQuestionOneOf2 getDecisionQuestionOneOf2() throws ClassCastException {
        return (DecisionQuestionOneOf2)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof DecisionQuestionOneOf) {
        if (getActualInstance() != null) {
          joiner.add(((DecisionQuestionOneOf)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DecisionQuestionOneOf1) {
        if (getActualInstance() != null) {
          joiner.add(((DecisionQuestionOneOf1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DecisionQuestionOneOf2) {
        if (getActualInstance() != null) {
          joiner.add(((DecisionQuestionOneOf2)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

