/*
 * Macrofold API
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * Organization-wide saved-trigger capacity, including paused definitions. Independent of delivery and execution limits.
 */
@JsonPropertyOrder({
  ListTriggers200ResponseQuota.JSON_PROPERTY_LIMIT,
  ListTriggers200ResponseQuota.JSON_PROPERTY_USED,
  ListTriggers200ResponseQuota.JSON_PROPERTY_REMAINING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ListTriggers200ResponseQuota {
  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_USED = "used";
  @javax.annotation.Nonnull
  private Integer used;

  public static final String JSON_PROPERTY_REMAINING = "remaining";
  @javax.annotation.Nonnull
  private Integer remaining;

  public ListTriggers200ResponseQuota() { 
  }

  public ListTriggers200ResponseQuota limit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * minimum: 0
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public ListTriggers200ResponseQuota used(@javax.annotation.Nonnull Integer used) {
    this.used = used;
    return this;
  }

  /**
   * Get used
   * minimum: 0
   * @return used
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getUsed() {
    return used;
  }


  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsed(@javax.annotation.Nonnull Integer used) {
    this.used = used;
  }


  public ListTriggers200ResponseQuota remaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
    return this;
  }

  /**
   * Get remaining
   * minimum: 0
   * @return remaining
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getRemaining() {
    return remaining;
  }


  @JsonProperty(value = JSON_PROPERTY_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
  }


  /**
   * Return true if this listTriggers_200_response_quota object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListTriggers200ResponseQuota listTriggers200ResponseQuota = (ListTriggers200ResponseQuota) o;
    return Objects.equals(this.limit, listTriggers200ResponseQuota.limit) &&
        Objects.equals(this.used, listTriggers200ResponseQuota.used) &&
        Objects.equals(this.remaining, listTriggers200ResponseQuota.remaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, used, remaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListTriggers200ResponseQuota {\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    remaining: ").append(toIndentedString(remaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `used` to the URL query string
    if (getUsed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sused%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsed()))));
    }

    // add `remaining` to the URL query string
    if (getRemaining() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sremaining%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRemaining()))));
    }

    return joiner.toString();
  }
}

