/*
 * Macrofold API
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * Recommendation
 */
@JsonPropertyOrder({
  Recommendation.JSON_PROPERTY_CODE,
  Recommendation.JSON_PROPERTY_SUMMARY,
  Recommendation.JSON_PROPERTY_EVIDENCE_METRIC_NAMES,
  Recommendation.JSON_PROPERTY_SAMPLE_SIZE,
  Recommendation.JSON_PROPERTY_SUGGESTED_ACTION,
  Recommendation.JSON_PROPERTY_ACTION_EXECUTED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Recommendation {
  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  public static final String JSON_PROPERTY_EVIDENCE_METRIC_NAMES = "evidence_metric_names";
  @javax.annotation.Nonnull
  private List<String> evidenceMetricNames = new ArrayList<>();

  public static final String JSON_PROPERTY_SAMPLE_SIZE = "sample_size";
  @javax.annotation.Nullable
  private String sampleSize;

  public static final String JSON_PROPERTY_SUGGESTED_ACTION = "suggested_action";
  @javax.annotation.Nonnull
  private String suggestedAction;

  /**
   * Gets or Sets actionExecuted
   */
  public enum ActionExecutedEnum {
    FALSE(Boolean.valueOf("false"));

    private Boolean value;

    ActionExecutedEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionExecutedEnum fromValue(Boolean value) {
      for (ActionExecutedEnum b : ActionExecutedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION_EXECUTED = "action_executed";
  @javax.annotation.Nonnull
  private ActionExecutedEnum actionExecuted;

  public Recommendation() { 
  }

  public Recommendation code(@javax.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public Recommendation summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public Recommendation evidenceMetricNames(@javax.annotation.Nonnull List<String> evidenceMetricNames) {
    this.evidenceMetricNames = evidenceMetricNames;
    return this;
  }

  public Recommendation addEvidenceMetricNamesItem(String evidenceMetricNamesItem) {
    if (this.evidenceMetricNames == null) {
      this.evidenceMetricNames = new ArrayList<>();
    }
    this.evidenceMetricNames.add(evidenceMetricNamesItem);
    return this;
  }

  /**
   * Get evidenceMetricNames
   * @return evidenceMetricNames
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVIDENCE_METRIC_NAMES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getEvidenceMetricNames() {
    return evidenceMetricNames;
  }


  @JsonProperty(value = JSON_PROPERTY_EVIDENCE_METRIC_NAMES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidenceMetricNames(@javax.annotation.Nonnull List<String> evidenceMetricNames) {
    this.evidenceMetricNames = evidenceMetricNames;
  }


  public Recommendation sampleSize(@javax.annotation.Nullable String sampleSize) {
    this.sampleSize = sampleSize;
    return this;
  }

  /**
   * Get sampleSize
   * @return sampleSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAMPLE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSampleSize() {
    return sampleSize;
  }


  @JsonProperty(value = JSON_PROPERTY_SAMPLE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleSize(@javax.annotation.Nullable String sampleSize) {
    this.sampleSize = sampleSize;
  }


  public Recommendation suggestedAction(@javax.annotation.Nonnull String suggestedAction) {
    this.suggestedAction = suggestedAction;
    return this;
  }

  /**
   * Get suggestedAction
   * @return suggestedAction
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUGGESTED_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSuggestedAction() {
    return suggestedAction;
  }


  @JsonProperty(value = JSON_PROPERTY_SUGGESTED_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuggestedAction(@javax.annotation.Nonnull String suggestedAction) {
    this.suggestedAction = suggestedAction;
  }


  public Recommendation actionExecuted(@javax.annotation.Nonnull ActionExecutedEnum actionExecuted) {
    this.actionExecuted = actionExecuted;
    return this;
  }

  /**
   * Get actionExecuted
   * @return actionExecuted
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION_EXECUTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ActionExecutedEnum getActionExecuted() {
    return actionExecuted;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION_EXECUTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActionExecuted(@javax.annotation.Nonnull ActionExecutedEnum actionExecuted) {
    this.actionExecuted = actionExecuted;
  }


  /**
   * Return true if this Recommendation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recommendation recommendation = (Recommendation) o;
    return Objects.equals(this.code, recommendation.code) &&
        Objects.equals(this.summary, recommendation.summary) &&
        Objects.equals(this.evidenceMetricNames, recommendation.evidenceMetricNames) &&
        Objects.equals(this.sampleSize, recommendation.sampleSize) &&
        Objects.equals(this.suggestedAction, recommendation.suggestedAction) &&
        Objects.equals(this.actionExecuted, recommendation.actionExecuted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, summary, evidenceMetricNames, sampleSize, suggestedAction, actionExecuted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recommendation {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    evidenceMetricNames: ").append(toIndentedString(evidenceMetricNames)).append("\n");
    sb.append("    sampleSize: ").append(toIndentedString(sampleSize)).append("\n");
    sb.append("    suggestedAction: ").append(toIndentedString(suggestedAction)).append("\n");
    sb.append("    actionExecuted: ").append(toIndentedString(actionExecuted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `evidence_metric_names` to the URL query string
    if (getEvidenceMetricNames() != null) {
      for (int i = 0; i < getEvidenceMetricNames().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sevidence_metric_names%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEvidenceMetricNames().get(i)))));
      }
    }

    // add `sample_size` to the URL query string
    if (getSampleSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssample_size%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSampleSize()))));
    }

    // add `suggested_action` to the URL query string
    if (getSuggestedAction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuggested_action%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuggestedAction()))));
    }

    // add `action_executed` to the URL query string
    if (getActionExecuted() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saction_executed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActionExecuted()))));
    }

    return joiner.toString();
  }
}

