/*
 * Macrofold API
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.macrofold.model.WorktreeSourceOneOf;
import dev.macrofold.model.WorktreeSourceOneOf1;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import dev.macrofold.ApiClient;
import dev.macrofold.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
@JsonDeserialize(using = WorktreeSource.WorktreeSourceDeserializer.class)
@JsonSerialize(using = WorktreeSource.WorktreeSourceSerializer.class)
public class WorktreeSource extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(WorktreeSource.class.getName());

    public static class WorktreeSourceSerializer extends StdSerializer<WorktreeSource> {
        public WorktreeSourceSerializer(Class<WorktreeSource> t) {
            super(t);
        }

        public WorktreeSourceSerializer() {
            this(null);
        }

        @Override
        public void serialize(WorktreeSource value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class WorktreeSourceDeserializer extends StdDeserializer<WorktreeSource> {
        public WorktreeSourceDeserializer() {
            this(WorktreeSource.class);
        }

        public WorktreeSourceDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public WorktreeSource deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize WorktreeSourceOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WorktreeSourceOneOf.class.equals(Integer.class) || WorktreeSourceOneOf.class.equals(Long.class) || WorktreeSourceOneOf.class.equals(Float.class) || WorktreeSourceOneOf.class.equals(Double.class) || WorktreeSourceOneOf.class.equals(Boolean.class) || WorktreeSourceOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WorktreeSourceOneOf.class.equals(Integer.class) || WorktreeSourceOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WorktreeSourceOneOf.class.equals(Float.class) || WorktreeSourceOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WorktreeSourceOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WorktreeSourceOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorktreeSourceOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorktreeSourceOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorktreeSourceOneOf'", e);
            }

            // deserialize WorktreeSourceOneOf1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WorktreeSourceOneOf1.class.equals(Integer.class) || WorktreeSourceOneOf1.class.equals(Long.class) || WorktreeSourceOneOf1.class.equals(Float.class) || WorktreeSourceOneOf1.class.equals(Double.class) || WorktreeSourceOneOf1.class.equals(Boolean.class) || WorktreeSourceOneOf1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WorktreeSourceOneOf1.class.equals(Integer.class) || WorktreeSourceOneOf1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WorktreeSourceOneOf1.class.equals(Float.class) || WorktreeSourceOneOf1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WorktreeSourceOneOf1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WorktreeSourceOneOf1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorktreeSourceOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorktreeSourceOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorktreeSourceOneOf1'", e);
            }

            if (match == 1) {
                WorktreeSource ret = new WorktreeSource();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for WorktreeSource: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public WorktreeSource getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "WorktreeSource cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public WorktreeSource() {
        super("oneOf", Boolean.FALSE);
    }

    public WorktreeSource(WorktreeSourceOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public WorktreeSource(WorktreeSourceOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("WorktreeSourceOneOf", WorktreeSourceOneOf.class);
        schemas.put("WorktreeSourceOneOf1", WorktreeSourceOneOf1.class);
        JSON.registerDescendants(WorktreeSource.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return WorktreeSource.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * WorktreeSourceOneOf, WorktreeSourceOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(WorktreeSourceOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WorktreeSourceOneOf1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be WorktreeSourceOneOf, WorktreeSourceOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * WorktreeSourceOneOf, WorktreeSourceOneOf1
     *
     * @return The actual instance (WorktreeSourceOneOf, WorktreeSourceOneOf1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorktreeSourceOneOf`. If the actual instance is not `WorktreeSourceOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorktreeSourceOneOf`
     * @throws ClassCastException if the instance is not `WorktreeSourceOneOf`
     */
    public WorktreeSourceOneOf getWorktreeSourceOneOf() throws ClassCastException {
        return (WorktreeSourceOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorktreeSourceOneOf1`. If the actual instance is not `WorktreeSourceOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorktreeSourceOneOf1`
     * @throws ClassCastException if the instance is not `WorktreeSourceOneOf1`
     */
    public WorktreeSourceOneOf1 getWorktreeSourceOneOf1() throws ClassCastException {
        return (WorktreeSourceOneOf1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof WorktreeSourceOneOf) {
        if (getActualInstance() != null) {
          joiner.add(((WorktreeSourceOneOf)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof WorktreeSourceOneOf1) {
        if (getActualInstance() != null) {
          joiner.add(((WorktreeSourceOneOf1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

