/*
 * Macrofold API
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * WorkspaceSourceOneOf1
 */
@JsonPropertyOrder({
  WorkspaceSourceOneOf1.JSON_PROPERTY_KIND,
  WorkspaceSourceOneOf1.JSON_PROPERTY_CHECKPOINT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class WorkspaceSourceOneOf1 {
  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private Object kind = null;

  public static final String JSON_PROPERTY_CHECKPOINT_ID = "checkpoint_id";
  @javax.annotation.Nonnull
  private UUID checkpointId;

  public WorkspaceSourceOneOf1() { 
  }

  public WorkspaceSourceOneOf1 kind(@javax.annotation.Nullable Object kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKind(@javax.annotation.Nullable Object kind) {
    this.kind = kind;
  }


  public WorkspaceSourceOneOf1 checkpointId(@javax.annotation.Nonnull UUID checkpointId) {
    this.checkpointId = checkpointId;
    return this;
  }

  /**
   * Get checkpointId
   * @return checkpointId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHECKPOINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getCheckpointId() {
    return checkpointId;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECKPOINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCheckpointId(@javax.annotation.Nonnull UUID checkpointId) {
    this.checkpointId = checkpointId;
  }


  /**
   * Return true if this WorkspaceSource_oneOf_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceSourceOneOf1 workspaceSourceOneOf1 = (WorkspaceSourceOneOf1) o;
    return Objects.equals(this.kind, workspaceSourceOneOf1.kind) &&
        Objects.equals(this.checkpointId, workspaceSourceOneOf1.checkpointId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, checkpointId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceSourceOneOf1 {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    checkpointId: ").append(toIndentedString(checkpointId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `checkpoint_id` to the URL query string
    if (getCheckpointId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scheckpoint_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCheckpointId()))));
    }

    return joiner.toString();
  }
}

