/*
 * Macrofold API
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.macrofold.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.macrofold.ApiClient;
/**
 * WorkspaceRemoteChange
 */
@JsonPropertyOrder({
  WorkspaceRemoteChange.JSON_PROPERTY_REF,
  WorkspaceRemoteChange.JSON_PROPERTY_OBSERVED_COMMIT,
  WorkspaceRemoteChange.JSON_PROPERTY_DELETED,
  WorkspaceRemoteChange.JSON_PROPERTY_RECEIVED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class WorkspaceRemoteChange {
  public static final String JSON_PROPERTY_REF = "ref";
  @javax.annotation.Nullable
  private String ref;

  public static final String JSON_PROPERTY_OBSERVED_COMMIT = "observed_commit";
  @javax.annotation.Nullable
  private String observedCommit;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private Boolean deleted;

  public static final String JSON_PROPERTY_RECEIVED_AT = "received_at";
  @javax.annotation.Nullable
  private OffsetDateTime receivedAt;

  public WorkspaceRemoteChange() { 
  }

  public WorkspaceRemoteChange ref(@javax.annotation.Nullable String ref) {
    this.ref = ref;
    return this;
  }

  /**
   * Get ref
   * @return ref
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRef() {
    return ref;
  }


  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRef(@javax.annotation.Nullable String ref) {
    this.ref = ref;
  }


  public WorkspaceRemoteChange observedCommit(@javax.annotation.Nullable String observedCommit) {
    this.observedCommit = observedCommit;
    return this;
  }

  /**
   * Get observedCommit
   * @return observedCommit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBSERVED_COMMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getObservedCommit() {
    return observedCommit;
  }


  @JsonProperty(value = JSON_PROPERTY_OBSERVED_COMMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObservedCommit(@javax.annotation.Nullable String observedCommit) {
    this.observedCommit = observedCommit;
  }


  public WorkspaceRemoteChange deleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
  }


  public WorkspaceRemoteChange receivedAt(@javax.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECEIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedAt(@javax.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  /**
   * Return true if this Workspace_remote_change object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceRemoteChange workspaceRemoteChange = (WorkspaceRemoteChange) o;
    return Objects.equals(this.ref, workspaceRemoteChange.ref) &&
        Objects.equals(this.observedCommit, workspaceRemoteChange.observedCommit) &&
        Objects.equals(this.deleted, workspaceRemoteChange.deleted) &&
        Objects.equals(this.receivedAt, workspaceRemoteChange.receivedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref, observedCommit, deleted, receivedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceRemoteChange {\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    observedCommit: ").append(toIndentedString(observedCommit)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ref` to the URL query string
    if (getRef() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sref%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRef()))));
    }

    // add `observed_commit` to the URL query string
    if (getObservedCommit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobserved_commit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObservedCommit()))));
    }

    // add `deleted` to the URL query string
    if (getDeleted() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeleted()))));
    }

    // add `received_at` to the URL query string
    if (getReceivedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreceived_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReceivedAt()))));
    }

    return joiner.toString();
  }
}

