/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectionAccessRuleMatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionAccessRuleMatch{}

// ConnectionAccessRuleMatch An authorized, bounded rule sample for explaining contextual access. Never use a sample as an authorization decision.
type ConnectionAccessRuleMatch struct {
	RuleId string `json:"rule_id"`
	Scope string `json:"scope"`
	WorkspaceId NullableString `json:"workspace_id,omitempty"`
	AgentId NullableString `json:"agent_id,omitempty"`
	WorkspaceName NullableString `json:"workspace_name,omitempty"`
	AgentName NullableString `json:"agent_name,omitempty"`
}

type _ConnectionAccessRuleMatch ConnectionAccessRuleMatch

// NewConnectionAccessRuleMatch instantiates a new ConnectionAccessRuleMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionAccessRuleMatch(ruleId string, scope string) *ConnectionAccessRuleMatch {
	this := ConnectionAccessRuleMatch{}
	this.RuleId = ruleId
	this.Scope = scope
	return &this
}

// NewConnectionAccessRuleMatchWithDefaults instantiates a new ConnectionAccessRuleMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionAccessRuleMatchWithDefaults() *ConnectionAccessRuleMatch {
	this := ConnectionAccessRuleMatch{}
	return &this
}

// GetRuleId returns the RuleId field value
func (o *ConnectionAccessRuleMatch) GetRuleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccessRuleMatch) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleId, true
}

// SetRuleId sets field value
func (o *ConnectionAccessRuleMatch) SetRuleId(v string) {
	o.RuleId = v
}

// GetScope returns the Scope field value
func (o *ConnectionAccessRuleMatch) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccessRuleMatch) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *ConnectionAccessRuleMatch) SetScope(v string) {
	o.Scope = v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionAccessRuleMatch) GetWorkspaceId() string {
	if o == nil || IsNil(o.WorkspaceId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkspaceId.Get()
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionAccessRuleMatch) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceId.Get(), o.WorkspaceId.IsSet()
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *ConnectionAccessRuleMatch) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId.IsSet() {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given NullableString and assigns it to the WorkspaceId field.
func (o *ConnectionAccessRuleMatch) SetWorkspaceId(v string) {
	o.WorkspaceId.Set(&v)
}
// SetWorkspaceIdNil sets the value for WorkspaceId to be an explicit nil
func (o *ConnectionAccessRuleMatch) SetWorkspaceIdNil() {
	o.WorkspaceId.Set(nil)
}

// UnsetWorkspaceId ensures that no value is present for WorkspaceId, not even an explicit nil
func (o *ConnectionAccessRuleMatch) UnsetWorkspaceId() {
	o.WorkspaceId.Unset()
}

// GetAgentId returns the AgentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionAccessRuleMatch) GetAgentId() string {
	if o == nil || IsNil(o.AgentId.Get()) {
		var ret string
		return ret
	}
	return *o.AgentId.Get()
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionAccessRuleMatch) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentId.Get(), o.AgentId.IsSet()
}

// HasAgentId returns a boolean if a field has been set.
func (o *ConnectionAccessRuleMatch) HasAgentId() bool {
	if o != nil && o.AgentId.IsSet() {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given NullableString and assigns it to the AgentId field.
func (o *ConnectionAccessRuleMatch) SetAgentId(v string) {
	o.AgentId.Set(&v)
}
// SetAgentIdNil sets the value for AgentId to be an explicit nil
func (o *ConnectionAccessRuleMatch) SetAgentIdNil() {
	o.AgentId.Set(nil)
}

// UnsetAgentId ensures that no value is present for AgentId, not even an explicit nil
func (o *ConnectionAccessRuleMatch) UnsetAgentId() {
	o.AgentId.Unset()
}

// GetWorkspaceName returns the WorkspaceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionAccessRuleMatch) GetWorkspaceName() string {
	if o == nil || IsNil(o.WorkspaceName.Get()) {
		var ret string
		return ret
	}
	return *o.WorkspaceName.Get()
}

// GetWorkspaceNameOk returns a tuple with the WorkspaceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionAccessRuleMatch) GetWorkspaceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceName.Get(), o.WorkspaceName.IsSet()
}

// HasWorkspaceName returns a boolean if a field has been set.
func (o *ConnectionAccessRuleMatch) HasWorkspaceName() bool {
	if o != nil && o.WorkspaceName.IsSet() {
		return true
	}

	return false
}

// SetWorkspaceName gets a reference to the given NullableString and assigns it to the WorkspaceName field.
func (o *ConnectionAccessRuleMatch) SetWorkspaceName(v string) {
	o.WorkspaceName.Set(&v)
}
// SetWorkspaceNameNil sets the value for WorkspaceName to be an explicit nil
func (o *ConnectionAccessRuleMatch) SetWorkspaceNameNil() {
	o.WorkspaceName.Set(nil)
}

// UnsetWorkspaceName ensures that no value is present for WorkspaceName, not even an explicit nil
func (o *ConnectionAccessRuleMatch) UnsetWorkspaceName() {
	o.WorkspaceName.Unset()
}

// GetAgentName returns the AgentName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionAccessRuleMatch) GetAgentName() string {
	if o == nil || IsNil(o.AgentName.Get()) {
		var ret string
		return ret
	}
	return *o.AgentName.Get()
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionAccessRuleMatch) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentName.Get(), o.AgentName.IsSet()
}

// HasAgentName returns a boolean if a field has been set.
func (o *ConnectionAccessRuleMatch) HasAgentName() bool {
	if o != nil && o.AgentName.IsSet() {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given NullableString and assigns it to the AgentName field.
func (o *ConnectionAccessRuleMatch) SetAgentName(v string) {
	o.AgentName.Set(&v)
}
// SetAgentNameNil sets the value for AgentName to be an explicit nil
func (o *ConnectionAccessRuleMatch) SetAgentNameNil() {
	o.AgentName.Set(nil)
}

// UnsetAgentName ensures that no value is present for AgentName, not even an explicit nil
func (o *ConnectionAccessRuleMatch) UnsetAgentName() {
	o.AgentName.Unset()
}

func (o ConnectionAccessRuleMatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionAccessRuleMatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rule_id"] = o.RuleId
	toSerialize["scope"] = o.Scope
	if o.WorkspaceId.IsSet() {
		toSerialize["workspace_id"] = o.WorkspaceId.Get()
	}
	if o.AgentId.IsSet() {
		toSerialize["agent_id"] = o.AgentId.Get()
	}
	if o.WorkspaceName.IsSet() {
		toSerialize["workspace_name"] = o.WorkspaceName.Get()
	}
	if o.AgentName.IsSet() {
		toSerialize["agent_name"] = o.AgentName.Get()
	}
	return toSerialize, nil
}

func (o *ConnectionAccessRuleMatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rule_id",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionAccessRuleMatch := _ConnectionAccessRuleMatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectionAccessRuleMatch)

	if err != nil {
		return err
	}

	*o = ConnectionAccessRuleMatch(varConnectionAccessRuleMatch)

	return err
}

type NullableConnectionAccessRuleMatch struct {
	value *ConnectionAccessRuleMatch
	isSet bool
}

func (v NullableConnectionAccessRuleMatch) Get() *ConnectionAccessRuleMatch {
	return v.value
}

func (v *NullableConnectionAccessRuleMatch) Set(val *ConnectionAccessRuleMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionAccessRuleMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionAccessRuleMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionAccessRuleMatch(val *ConnectionAccessRuleMatch) *NullableConnectionAccessRuleMatch {
	return &NullableConnectionAccessRuleMatch{value: val, isSet: true}
}

func (v NullableConnectionAccessRuleMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionAccessRuleMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


