/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerAgentMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerAgentMessage{}

// CustomerAgentMessage Omit conversation_id for a new native conversation over the same files. An existing conversation must belong to this binding. Only explicitly selected customer connections are used; no organization-wide inheritance.
type CustomerAgentMessage struct {
	Prompt string `json:"prompt"`
	ConversationId *string `json:"conversation_id,omitempty"`
	Limits *Limits `json:"limits,omitempty"`
	// Queue when this worktree is busy. Omitted means false.
	QueueIfBusy *bool `json:"queue_if_busy,omitempty"`
	// Paths of files already uploaded to this worktree. Requires files:read. PNG/JPEG/WebP use native image input on supported Codex/Claude Code models; PDF/DOCX/TXT/MD/CSV/JSON are extracted to bounded text. Five files, 20 MiB total; images 1 MiB and 2048 px per side; documents 10 MiB. The admitted content hash must still match at execution. Audio/video analysis is not supported.
	Attachments []string `json:"attachments,omitempty"`
}

type _CustomerAgentMessage CustomerAgentMessage

// NewCustomerAgentMessage instantiates a new CustomerAgentMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerAgentMessage(prompt string) *CustomerAgentMessage {
	this := CustomerAgentMessage{}
	this.Prompt = prompt
	return &this
}

// NewCustomerAgentMessageWithDefaults instantiates a new CustomerAgentMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerAgentMessageWithDefaults() *CustomerAgentMessage {
	this := CustomerAgentMessage{}
	return &this
}

// GetPrompt returns the Prompt field value
func (o *CustomerAgentMessage) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *CustomerAgentMessage) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *CustomerAgentMessage) SetPrompt(v string) {
	o.Prompt = v
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *CustomerAgentMessage) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAgentMessage) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *CustomerAgentMessage) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *CustomerAgentMessage) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *CustomerAgentMessage) GetLimits() Limits {
	if o == nil || IsNil(o.Limits) {
		var ret Limits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAgentMessage) GetLimitsOk() (*Limits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *CustomerAgentMessage) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given Limits and assigns it to the Limits field.
func (o *CustomerAgentMessage) SetLimits(v Limits) {
	o.Limits = &v
}

// GetQueueIfBusy returns the QueueIfBusy field value if set, zero value otherwise.
func (o *CustomerAgentMessage) GetQueueIfBusy() bool {
	if o == nil || IsNil(o.QueueIfBusy) {
		var ret bool
		return ret
	}
	return *o.QueueIfBusy
}

// GetQueueIfBusyOk returns a tuple with the QueueIfBusy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAgentMessage) GetQueueIfBusyOk() (*bool, bool) {
	if o == nil || IsNil(o.QueueIfBusy) {
		return nil, false
	}
	return o.QueueIfBusy, true
}

// HasQueueIfBusy returns a boolean if a field has been set.
func (o *CustomerAgentMessage) HasQueueIfBusy() bool {
	if o != nil && !IsNil(o.QueueIfBusy) {
		return true
	}

	return false
}

// SetQueueIfBusy gets a reference to the given bool and assigns it to the QueueIfBusy field.
func (o *CustomerAgentMessage) SetQueueIfBusy(v bool) {
	o.QueueIfBusy = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *CustomerAgentMessage) GetAttachments() []string {
	if o == nil || IsNil(o.Attachments) {
		var ret []string
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerAgentMessage) GetAttachmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *CustomerAgentMessage) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []string and assigns it to the Attachments field.
func (o *CustomerAgentMessage) SetAttachments(v []string) {
	o.Attachments = v
}

func (o CustomerAgentMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerAgentMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt"] = o.Prompt
	if !IsNil(o.ConversationId) {
		toSerialize["conversation_id"] = o.ConversationId
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.QueueIfBusy) {
		toSerialize["queue_if_busy"] = o.QueueIfBusy
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	return toSerialize, nil
}

func (o *CustomerAgentMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerAgentMessage := _CustomerAgentMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerAgentMessage)

	if err != nil {
		return err
	}

	*o = CustomerAgentMessage(varCustomerAgentMessage)

	return err
}

type NullableCustomerAgentMessage struct {
	value *CustomerAgentMessage
	isSet bool
}

func (v NullableCustomerAgentMessage) Get() *CustomerAgentMessage {
	return v.value
}

func (v *NullableCustomerAgentMessage) Set(val *CustomerAgentMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAgentMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAgentMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerAgentMessage(val *CustomerAgentMessage) *NullableCustomerAgentMessage {
	return &NullableCustomerAgentMessage{value: val, isSet: true}
}

func (v NullableCustomerAgentMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAgentMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


