/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingUsageEntryStorage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingUsageEntryStorage{}

// BillingUsageEntryStorage struct for BillingUsageEntryStorage
type BillingUsageEntryStorage struct {
	PhysicalBytes string `json:"physical_bytes" validate:"regexp=^[0-9]+$"`
	ObjectCount string `json:"object_count" validate:"regexp=^[0-9]+$"`
}

type _BillingUsageEntryStorage BillingUsageEntryStorage

// NewBillingUsageEntryStorage instantiates a new BillingUsageEntryStorage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingUsageEntryStorage(physicalBytes string, objectCount string) *BillingUsageEntryStorage {
	this := BillingUsageEntryStorage{}
	this.PhysicalBytes = physicalBytes
	this.ObjectCount = objectCount
	return &this
}

// NewBillingUsageEntryStorageWithDefaults instantiates a new BillingUsageEntryStorage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingUsageEntryStorageWithDefaults() *BillingUsageEntryStorage {
	this := BillingUsageEntryStorage{}
	return &this
}

// GetPhysicalBytes returns the PhysicalBytes field value
func (o *BillingUsageEntryStorage) GetPhysicalBytes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhysicalBytes
}

// GetPhysicalBytesOk returns a tuple with the PhysicalBytes field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEntryStorage) GetPhysicalBytesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhysicalBytes, true
}

// SetPhysicalBytes sets field value
func (o *BillingUsageEntryStorage) SetPhysicalBytes(v string) {
	o.PhysicalBytes = v
}

// GetObjectCount returns the ObjectCount field value
func (o *BillingUsageEntryStorage) GetObjectCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectCount
}

// GetObjectCountOk returns a tuple with the ObjectCount field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEntryStorage) GetObjectCountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectCount, true
}

// SetObjectCount sets field value
func (o *BillingUsageEntryStorage) SetObjectCount(v string) {
	o.ObjectCount = v
}

func (o BillingUsageEntryStorage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingUsageEntryStorage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["physical_bytes"] = o.PhysicalBytes
	toSerialize["object_count"] = o.ObjectCount
	return toSerialize, nil
}

func (o *BillingUsageEntryStorage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"physical_bytes",
		"object_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingUsageEntryStorage := _BillingUsageEntryStorage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingUsageEntryStorage)

	if err != nil {
		return err
	}

	*o = BillingUsageEntryStorage(varBillingUsageEntryStorage)

	return err
}

type NullableBillingUsageEntryStorage struct {
	value *BillingUsageEntryStorage
	isSet bool
}

func (v NullableBillingUsageEntryStorage) Get() *BillingUsageEntryStorage {
	return v.value
}

func (v *NullableBillingUsageEntryStorage) Set(val *BillingUsageEntryStorage) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingUsageEntryStorage) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingUsageEntryStorage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingUsageEntryStorage(val *BillingUsageEntryStorage) *NullableBillingUsageEntryStorage {
	return &NullableBillingUsageEntryStorage{value: val, isSet: true}
}

func (v NullableBillingUsageEntryStorage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingUsageEntryStorage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


