/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreatedApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedApiKey{}

// CreatedApiKey struct for CreatedApiKey
type CreatedApiKey struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Prefix string `json:"prefix"`
	Scopes []string `json:"scopes"`
	ProjectId *string `json:"project_id,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Displayed once at creation; never returned again.
	Secret string `json:"secret"`
}

type _CreatedApiKey CreatedApiKey

// NewCreatedApiKey instantiates a new CreatedApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedApiKey(id string, name string, prefix string, scopes []string, secret string) *CreatedApiKey {
	this := CreatedApiKey{}
	this.Id = id
	this.Name = name
	this.Prefix = prefix
	this.Scopes = scopes
	this.Secret = secret
	return &this
}

// NewCreatedApiKeyWithDefaults instantiates a new CreatedApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedApiKeyWithDefaults() *CreatedApiKey {
	this := CreatedApiKey{}
	return &this
}

// GetId returns the Id field value
func (o *CreatedApiKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreatedApiKey) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreatedApiKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatedApiKey) SetName(v string) {
	o.Name = v
}

// GetPrefix returns the Prefix field value
func (o *CreatedApiKey) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *CreatedApiKey) SetPrefix(v string) {
	o.Prefix = v
}

// GetScopes returns the Scopes field value
func (o *CreatedApiKey) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *CreatedApiKey) SetScopes(v []string) {
	o.Scopes = v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreatedApiKey) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreatedApiKey) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CreatedApiKey) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *CreatedApiKey) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *CreatedApiKey) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given time.Time and assigns it to the LastUsedAt field.
func (o *CreatedApiKey) SetLastUsedAt(v time.Time) {
	o.LastUsedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *CreatedApiKey) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreatedApiKey) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *CreatedApiKey) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *CreatedApiKey) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *CreatedApiKey) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given time.Time and assigns it to the RevokedAt field.
func (o *CreatedApiKey) SetRevokedAt(v time.Time) {
	o.RevokedAt = &v
}

// GetSecret returns the Secret field value
func (o *CreatedApiKey) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CreatedApiKey) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CreatedApiKey) SetSecret(v string) {
	o.Secret = v
}

func (o CreatedApiKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["prefix"] = o.Prefix
	toSerialize["scopes"] = o.Scopes
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *CreatedApiKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"prefix",
		"scopes",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatedApiKey := _CreatedApiKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatedApiKey)

	if err != nil {
		return err
	}

	*o = CreatedApiKey(varCreatedApiKey)

	return err
}

type NullableCreatedApiKey struct {
	value *CreatedApiKey
	isSet bool
}

func (v NullableCreatedApiKey) Get() *CreatedApiKey {
	return v.value
}

func (v *NullableCreatedApiKey) Set(val *CreatedApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedApiKey(val *CreatedApiKey) *NullableCreatedApiKey {
	return &NullableCreatedApiKey{value: val, isSet: true}
}

func (v NullableCreatedApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


