/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TaskOutcomeReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskOutcomeReceipt{}

// TaskOutcomeReceipt struct for TaskOutcomeReceipt
type TaskOutcomeReceipt struct {
	Id string `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Receipt ApplicationOutcome `json:"receipt"`
}

type _TaskOutcomeReceipt TaskOutcomeReceipt

// NewTaskOutcomeReceipt instantiates a new TaskOutcomeReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskOutcomeReceipt(id string, createdAt time.Time, receipt ApplicationOutcome) *TaskOutcomeReceipt {
	this := TaskOutcomeReceipt{}
	this.Id = id
	this.CreatedAt = createdAt
	this.Receipt = receipt
	return &this
}

// NewTaskOutcomeReceiptWithDefaults instantiates a new TaskOutcomeReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskOutcomeReceiptWithDefaults() *TaskOutcomeReceipt {
	this := TaskOutcomeReceipt{}
	return &this
}

// GetId returns the Id field value
func (o *TaskOutcomeReceipt) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TaskOutcomeReceipt) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TaskOutcomeReceipt) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TaskOutcomeReceipt) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TaskOutcomeReceipt) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TaskOutcomeReceipt) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetReceipt returns the Receipt field value
func (o *TaskOutcomeReceipt) GetReceipt() ApplicationOutcome {
	if o == nil {
		var ret ApplicationOutcome
		return ret
	}

	return o.Receipt
}

// GetReceiptOk returns a tuple with the Receipt field value
// and a boolean to check if the value has been set.
func (o *TaskOutcomeReceipt) GetReceiptOk() (*ApplicationOutcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receipt, true
}

// SetReceipt sets field value
func (o *TaskOutcomeReceipt) SetReceipt(v ApplicationOutcome) {
	o.Receipt = v
}

func (o TaskOutcomeReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskOutcomeReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["receipt"] = o.Receipt
	return toSerialize, nil
}

func (o *TaskOutcomeReceipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"receipt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskOutcomeReceipt := _TaskOutcomeReceipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskOutcomeReceipt)

	if err != nil {
		return err
	}

	*o = TaskOutcomeReceipt(varTaskOutcomeReceipt)

	return err
}

type NullableTaskOutcomeReceipt struct {
	value *TaskOutcomeReceipt
	isSet bool
}

func (v NullableTaskOutcomeReceipt) Get() *TaskOutcomeReceipt {
	return v.value
}

func (v *NullableTaskOutcomeReceipt) Set(val *TaskOutcomeReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskOutcomeReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskOutcomeReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskOutcomeReceipt(val *TaskOutcomeReceipt) *NullableTaskOutcomeReceipt {
	return &NullableTaskOutcomeReceipt{value: val, isSet: true}
}

func (v NullableTaskOutcomeReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskOutcomeReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


