/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SandboxCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxCreate{}

// SandboxCreate Disposable compute attached to one worktree. A long-running sandbox with omitted keep_warm_seconds stays ready until paused, destroyed, or its compute allocation is exhausted. Poll its status before starting latency-sensitive work.
type SandboxCreate struct {
	WorktreeId string `json:"worktree_id"`
	Name *string `json:"name,omitempty"`
	// Keep compute running between agents without a default idle timeout: Docker locally, Render in hosted deployments. The filesystem is disposable; successive agents reuse the same compute environment. Ordinary sandboxes retain bounded lifetimes.
	LongRunning *bool `json:"long_running,omitempty"`
	// Seconds to retain idle compute after a run. 0 or null on a run releases compute. Omitted inherits the sandbox policy.
	KeepWarmSeconds NullableInt32 `json:"keep_warm_seconds,omitempty"`
	// Separate prepaid compute allocation, covering ready and idle time until pause/destroy or exhaustion. Each explicit resume authorizes another allocation of this size. Model/tool costs retain the run budget.
	MaxCostMicroUsd *string `json:"max_cost_micro_usd,omitempty" validate:"regexp=^[0-9]{1\\,12}$"`
}

type _SandboxCreate SandboxCreate

// NewSandboxCreate instantiates a new SandboxCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxCreate(worktreeId string) *SandboxCreate {
	this := SandboxCreate{}
	this.WorktreeId = worktreeId
	return &this
}

// NewSandboxCreateWithDefaults instantiates a new SandboxCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxCreateWithDefaults() *SandboxCreate {
	this := SandboxCreate{}
	return &this
}

// GetWorktreeId returns the WorktreeId field value
func (o *SandboxCreate) GetWorktreeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorktreeId
}

// GetWorktreeIdOk returns a tuple with the WorktreeId field value
// and a boolean to check if the value has been set.
func (o *SandboxCreate) GetWorktreeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorktreeId, true
}

// SetWorktreeId sets field value
func (o *SandboxCreate) SetWorktreeId(v string) {
	o.WorktreeId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SandboxCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SandboxCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SandboxCreate) SetName(v string) {
	o.Name = &v
}

// GetLongRunning returns the LongRunning field value if set, zero value otherwise.
func (o *SandboxCreate) GetLongRunning() bool {
	if o == nil || IsNil(o.LongRunning) {
		var ret bool
		return ret
	}
	return *o.LongRunning
}

// GetLongRunningOk returns a tuple with the LongRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreate) GetLongRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.LongRunning) {
		return nil, false
	}
	return o.LongRunning, true
}

// HasLongRunning returns a boolean if a field has been set.
func (o *SandboxCreate) HasLongRunning() bool {
	if o != nil && !IsNil(o.LongRunning) {
		return true
	}

	return false
}

// SetLongRunning gets a reference to the given bool and assigns it to the LongRunning field.
func (o *SandboxCreate) SetLongRunning(v bool) {
	o.LongRunning = &v
}

// GetKeepWarmSeconds returns the KeepWarmSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SandboxCreate) GetKeepWarmSeconds() int32 {
	if o == nil || IsNil(o.KeepWarmSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.KeepWarmSeconds.Get()
}

// GetKeepWarmSecondsOk returns a tuple with the KeepWarmSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SandboxCreate) GetKeepWarmSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeepWarmSeconds.Get(), o.KeepWarmSeconds.IsSet()
}

// HasKeepWarmSeconds returns a boolean if a field has been set.
func (o *SandboxCreate) HasKeepWarmSeconds() bool {
	if o != nil && o.KeepWarmSeconds.IsSet() {
		return true
	}

	return false
}

// SetKeepWarmSeconds gets a reference to the given NullableInt32 and assigns it to the KeepWarmSeconds field.
func (o *SandboxCreate) SetKeepWarmSeconds(v int32) {
	o.KeepWarmSeconds.Set(&v)
}
// SetKeepWarmSecondsNil sets the value for KeepWarmSeconds to be an explicit nil
func (o *SandboxCreate) SetKeepWarmSecondsNil() {
	o.KeepWarmSeconds.Set(nil)
}

// UnsetKeepWarmSeconds ensures that no value is present for KeepWarmSeconds, not even an explicit nil
func (o *SandboxCreate) UnsetKeepWarmSeconds() {
	o.KeepWarmSeconds.Unset()
}

// GetMaxCostMicroUsd returns the MaxCostMicroUsd field value if set, zero value otherwise.
func (o *SandboxCreate) GetMaxCostMicroUsd() string {
	if o == nil || IsNil(o.MaxCostMicroUsd) {
		var ret string
		return ret
	}
	return *o.MaxCostMicroUsd
}

// GetMaxCostMicroUsdOk returns a tuple with the MaxCostMicroUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreate) GetMaxCostMicroUsdOk() (*string, bool) {
	if o == nil || IsNil(o.MaxCostMicroUsd) {
		return nil, false
	}
	return o.MaxCostMicroUsd, true
}

// HasMaxCostMicroUsd returns a boolean if a field has been set.
func (o *SandboxCreate) HasMaxCostMicroUsd() bool {
	if o != nil && !IsNil(o.MaxCostMicroUsd) {
		return true
	}

	return false
}

// SetMaxCostMicroUsd gets a reference to the given string and assigns it to the MaxCostMicroUsd field.
func (o *SandboxCreate) SetMaxCostMicroUsd(v string) {
	o.MaxCostMicroUsd = &v
}

func (o SandboxCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["worktree_id"] = o.WorktreeId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.LongRunning) {
		toSerialize["long_running"] = o.LongRunning
	}
	if o.KeepWarmSeconds.IsSet() {
		toSerialize["keep_warm_seconds"] = o.KeepWarmSeconds.Get()
	}
	if !IsNil(o.MaxCostMicroUsd) {
		toSerialize["max_cost_micro_usd"] = o.MaxCostMicroUsd
	}
	return toSerialize, nil
}

func (o *SandboxCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"worktree_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSandboxCreate := _SandboxCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSandboxCreate)

	if err != nil {
		return err
	}

	*o = SandboxCreate(varSandboxCreate)

	return err
}

type NullableSandboxCreate struct {
	value *SandboxCreate
	isSet bool
}

func (v NullableSandboxCreate) Get() *SandboxCreate {
	return v.value
}

func (v *NullableSandboxCreate) Set(val *SandboxCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxCreate(val *SandboxCreate) *NullableSandboxCreate {
	return &NullableSandboxCreate{value: val, isSet: true}
}

func (v NullableSandboxCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


