/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectionAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionAccess{}

// ConnectionAccess struct for ConnectionAccess
type ConnectionAccess struct {
	ConnectionId string `json:"connection_id"`
	Version string `json:"version" validate:"regexp=^[1-9][0-9]*$"`
	OrganizationWide bool `json:"organization_wide"`
	Tools []string `json:"tools"`
	RuleCount int32 `json:"rule_count"`
	CanGrant bool `json:"can_grant"`
	CanRevoke bool `json:"can_revoke"`
}

type _ConnectionAccess ConnectionAccess

// NewConnectionAccess instantiates a new ConnectionAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionAccess(connectionId string, version string, organizationWide bool, tools []string, ruleCount int32, canGrant bool, canRevoke bool) *ConnectionAccess {
	this := ConnectionAccess{}
	this.ConnectionId = connectionId
	this.Version = version
	this.OrganizationWide = organizationWide
	this.Tools = tools
	this.RuleCount = ruleCount
	this.CanGrant = canGrant
	this.CanRevoke = canRevoke
	return &this
}

// NewConnectionAccessWithDefaults instantiates a new ConnectionAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionAccessWithDefaults() *ConnectionAccess {
	this := ConnectionAccess{}
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *ConnectionAccess) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetConnectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *ConnectionAccess) SetConnectionId(v string) {
	o.ConnectionId = v
}

// GetVersion returns the Version field value
func (o *ConnectionAccess) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ConnectionAccess) SetVersion(v string) {
	o.Version = v
}

// GetOrganizationWide returns the OrganizationWide field value
func (o *ConnectionAccess) GetOrganizationWide() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OrganizationWide
}

// GetOrganizationWideOk returns a tuple with the OrganizationWide field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetOrganizationWideOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationWide, true
}

// SetOrganizationWide sets field value
func (o *ConnectionAccess) SetOrganizationWide(v bool) {
	o.OrganizationWide = v
}

// GetTools returns the Tools field value
func (o *ConnectionAccess) GetTools() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetToolsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools, true
}

// SetTools sets field value
func (o *ConnectionAccess) SetTools(v []string) {
	o.Tools = v
}

// GetRuleCount returns the RuleCount field value
func (o *ConnectionAccess) GetRuleCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RuleCount
}

// GetRuleCountOk returns a tuple with the RuleCount field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetRuleCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleCount, true
}

// SetRuleCount sets field value
func (o *ConnectionAccess) SetRuleCount(v int32) {
	o.RuleCount = v
}

// GetCanGrant returns the CanGrant field value
func (o *ConnectionAccess) GetCanGrant() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanGrant
}

// GetCanGrantOk returns a tuple with the CanGrant field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetCanGrantOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanGrant, true
}

// SetCanGrant sets field value
func (o *ConnectionAccess) SetCanGrant(v bool) {
	o.CanGrant = v
}

// GetCanRevoke returns the CanRevoke field value
func (o *ConnectionAccess) GetCanRevoke() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanRevoke
}

// GetCanRevokeOk returns a tuple with the CanRevoke field value
// and a boolean to check if the value has been set.
func (o *ConnectionAccess) GetCanRevokeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanRevoke, true
}

// SetCanRevoke sets field value
func (o *ConnectionAccess) SetCanRevoke(v bool) {
	o.CanRevoke = v
}

func (o ConnectionAccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection_id"] = o.ConnectionId
	toSerialize["version"] = o.Version
	toSerialize["organization_wide"] = o.OrganizationWide
	toSerialize["tools"] = o.Tools
	toSerialize["rule_count"] = o.RuleCount
	toSerialize["can_grant"] = o.CanGrant
	toSerialize["can_revoke"] = o.CanRevoke
	return toSerialize, nil
}

func (o *ConnectionAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection_id",
		"version",
		"organization_wide",
		"tools",
		"rule_count",
		"can_grant",
		"can_revoke",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionAccess := _ConnectionAccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectionAccess)

	if err != nil {
		return err
	}

	*o = ConnectionAccess(varConnectionAccess)

	return err
}

type NullableConnectionAccess struct {
	value *ConnectionAccess
	isSet bool
}

func (v NullableConnectionAccess) Get() *ConnectionAccess {
	return v.value
}

func (v *NullableConnectionAccess) Set(val *ConnectionAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionAccess(val *ConnectionAccess) *NullableConnectionAccess {
	return &NullableConnectionAccess{value: val, isSet: true}
}

func (v NullableConnectionAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


