/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GithubRepositoriesDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubRepositoriesDataInner{}

// GithubRepositoriesDataInner struct for GithubRepositoriesDataInner
type GithubRepositoriesDataInner struct {
	RepositoryId string `json:"repository_id"`
	FullName string `json:"full_name"`
	DefaultBranch string `json:"default_branch"`
}

type _GithubRepositoriesDataInner GithubRepositoriesDataInner

// NewGithubRepositoriesDataInner instantiates a new GithubRepositoriesDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubRepositoriesDataInner(repositoryId string, fullName string, defaultBranch string) *GithubRepositoriesDataInner {
	this := GithubRepositoriesDataInner{}
	this.RepositoryId = repositoryId
	this.FullName = fullName
	this.DefaultBranch = defaultBranch
	return &this
}

// NewGithubRepositoriesDataInnerWithDefaults instantiates a new GithubRepositoriesDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubRepositoriesDataInnerWithDefaults() *GithubRepositoriesDataInner {
	this := GithubRepositoriesDataInner{}
	return &this
}

// GetRepositoryId returns the RepositoryId field value
func (o *GithubRepositoriesDataInner) GetRepositoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value
// and a boolean to check if the value has been set.
func (o *GithubRepositoriesDataInner) GetRepositoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepositoryId, true
}

// SetRepositoryId sets field value
func (o *GithubRepositoriesDataInner) SetRepositoryId(v string) {
	o.RepositoryId = v
}

// GetFullName returns the FullName field value
func (o *GithubRepositoriesDataInner) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *GithubRepositoriesDataInner) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *GithubRepositoriesDataInner) SetFullName(v string) {
	o.FullName = v
}

// GetDefaultBranch returns the DefaultBranch field value
func (o *GithubRepositoriesDataInner) GetDefaultBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultBranch
}

// GetDefaultBranchOk returns a tuple with the DefaultBranch field value
// and a boolean to check if the value has been set.
func (o *GithubRepositoriesDataInner) GetDefaultBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultBranch, true
}

// SetDefaultBranch sets field value
func (o *GithubRepositoriesDataInner) SetDefaultBranch(v string) {
	o.DefaultBranch = v
}

func (o GithubRepositoriesDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubRepositoriesDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["repository_id"] = o.RepositoryId
	toSerialize["full_name"] = o.FullName
	toSerialize["default_branch"] = o.DefaultBranch
	return toSerialize, nil
}

func (o *GithubRepositoriesDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"repository_id",
		"full_name",
		"default_branch",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGithubRepositoriesDataInner := _GithubRepositoriesDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGithubRepositoriesDataInner)

	if err != nil {
		return err
	}

	*o = GithubRepositoriesDataInner(varGithubRepositoriesDataInner)

	return err
}

type NullableGithubRepositoriesDataInner struct {
	value *GithubRepositoriesDataInner
	isSet bool
}

func (v NullableGithubRepositoriesDataInner) Get() *GithubRepositoriesDataInner {
	return v.value
}

func (v *NullableGithubRepositoriesDataInner) Set(val *GithubRepositoriesDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubRepositoriesDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubRepositoriesDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubRepositoriesDataInner(val *GithubRepositoriesDataInner) *NullableGithubRepositoriesDataInner {
	return &NullableGithubRepositoriesDataInner{value: val, isSet: true}
}

func (v NullableGithubRepositoriesDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubRepositoriesDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


