/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InferenceCreateContext - struct for InferenceCreateContext
type InferenceCreateContext struct {
	ContextReference *ContextReference
	ExplicitContext *ExplicitContext
}

// ContextReferenceAsInferenceCreateContext is a convenience function that returns ContextReference wrapped in InferenceCreateContext
func ContextReferenceAsInferenceCreateContext(v *ContextReference) InferenceCreateContext {
	return InferenceCreateContext{
		ContextReference: v,
	}
}

// ExplicitContextAsInferenceCreateContext is a convenience function that returns ExplicitContext wrapped in InferenceCreateContext
func ExplicitContextAsInferenceCreateContext(v *ExplicitContext) InferenceCreateContext {
	return InferenceCreateContext{
		ExplicitContext: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InferenceCreateContext) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ContextReference
	err = newStrictDecoder(data).Decode(&dst.ContextReference)
	if err == nil {
		jsonContextReference, _ := json.Marshal(dst.ContextReference)
		if string(jsonContextReference) == "{}" { // empty struct
			dst.ContextReference = nil
		} else {
			if err = validator.Validate(dst.ContextReference); err != nil {
				dst.ContextReference = nil
			} else {
				match++
			}
		}
	} else {
		dst.ContextReference = nil
	}

	// try to unmarshal data into ExplicitContext
	err = newStrictDecoder(data).Decode(&dst.ExplicitContext)
	if err == nil {
		jsonExplicitContext, _ := json.Marshal(dst.ExplicitContext)
		if string(jsonExplicitContext) == "{}" { // empty struct
			dst.ExplicitContext = nil
		} else {
			if err = validator.Validate(dst.ExplicitContext); err != nil {
				dst.ExplicitContext = nil
			} else {
				match++
			}
		}
	} else {
		dst.ExplicitContext = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ContextReference = nil
		dst.ExplicitContext = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InferenceCreateContext)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InferenceCreateContext): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InferenceCreateContext)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InferenceCreateContext): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InferenceCreateContext)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InferenceCreateContext) MarshalJSON() ([]byte, error) {
	if src.ContextReference != nil {
		return json.Marshal(&src.ContextReference)
	}

	if src.ExplicitContext != nil {
		return json.Marshal(&src.ExplicitContext)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InferenceCreateContext) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ContextReference != nil {
		return obj.ContextReference
	}

	if obj.ExplicitContext != nil {
		return obj.ExplicitContext
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InferenceCreateContext) GetActualInstanceValue() (interface{}) {
	if obj.ContextReference != nil {
		return *obj.ContextReference
	}

	if obj.ExplicitContext != nil {
		return *obj.ExplicitContext
	}

	// all schemas are nil
	return nil
}

type NullableInferenceCreateContext struct {
	value *InferenceCreateContext
	isSet bool
}

func (v NullableInferenceCreateContext) Get() *InferenceCreateContext {
	return v.value
}

func (v *NullableInferenceCreateContext) Set(val *InferenceCreateContext) {
	v.value = val
	v.isSet = true
}

func (v NullableInferenceCreateContext) IsSet() bool {
	return v.isSet
}

func (v *NullableInferenceCreateContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInferenceCreateContext(val *InferenceCreateContext) *NullableInferenceCreateContext {
	return &NullableInferenceCreateContext{value: val, isSet: true}
}

func (v NullableInferenceCreateContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInferenceCreateContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


