/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"time"
)

// checks if the WorkspaceRemoteChange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceRemoteChange{}

// WorkspaceRemoteChange struct for WorkspaceRemoteChange
type WorkspaceRemoteChange struct {
	Ref *string `json:"ref,omitempty"`
	ObservedCommit *string `json:"observed_commit,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
	ReceivedAt *time.Time `json:"received_at,omitempty"`
}

// NewWorkspaceRemoteChange instantiates a new WorkspaceRemoteChange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceRemoteChange() *WorkspaceRemoteChange {
	this := WorkspaceRemoteChange{}
	return &this
}

// NewWorkspaceRemoteChangeWithDefaults instantiates a new WorkspaceRemoteChange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceRemoteChangeWithDefaults() *WorkspaceRemoteChange {
	this := WorkspaceRemoteChange{}
	return &this
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *WorkspaceRemoteChange) GetRef() string {
	if o == nil || IsNil(o.Ref) {
		var ret string
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceRemoteChange) GetRefOk() (*string, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *WorkspaceRemoteChange) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given string and assigns it to the Ref field.
func (o *WorkspaceRemoteChange) SetRef(v string) {
	o.Ref = &v
}

// GetObservedCommit returns the ObservedCommit field value if set, zero value otherwise.
func (o *WorkspaceRemoteChange) GetObservedCommit() string {
	if o == nil || IsNil(o.ObservedCommit) {
		var ret string
		return ret
	}
	return *o.ObservedCommit
}

// GetObservedCommitOk returns a tuple with the ObservedCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceRemoteChange) GetObservedCommitOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedCommit) {
		return nil, false
	}
	return o.ObservedCommit, true
}

// HasObservedCommit returns a boolean if a field has been set.
func (o *WorkspaceRemoteChange) HasObservedCommit() bool {
	if o != nil && !IsNil(o.ObservedCommit) {
		return true
	}

	return false
}

// SetObservedCommit gets a reference to the given string and assigns it to the ObservedCommit field.
func (o *WorkspaceRemoteChange) SetObservedCommit(v string) {
	o.ObservedCommit = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *WorkspaceRemoteChange) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceRemoteChange) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *WorkspaceRemoteChange) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *WorkspaceRemoteChange) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetReceivedAt returns the ReceivedAt field value if set, zero value otherwise.
func (o *WorkspaceRemoteChange) GetReceivedAt() time.Time {
	if o == nil || IsNil(o.ReceivedAt) {
		var ret time.Time
		return ret
	}
	return *o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceRemoteChange) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReceivedAt) {
		return nil, false
	}
	return o.ReceivedAt, true
}

// HasReceivedAt returns a boolean if a field has been set.
func (o *WorkspaceRemoteChange) HasReceivedAt() bool {
	if o != nil && !IsNil(o.ReceivedAt) {
		return true
	}

	return false
}

// SetReceivedAt gets a reference to the given time.Time and assigns it to the ReceivedAt field.
func (o *WorkspaceRemoteChange) SetReceivedAt(v time.Time) {
	o.ReceivedAt = &v
}

func (o WorkspaceRemoteChange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceRemoteChange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	if !IsNil(o.ObservedCommit) {
		toSerialize["observed_commit"] = o.ObservedCommit
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.ReceivedAt) {
		toSerialize["received_at"] = o.ReceivedAt
	}
	return toSerialize, nil
}

type NullableWorkspaceRemoteChange struct {
	value *WorkspaceRemoteChange
	isSet bool
}

func (v NullableWorkspaceRemoteChange) Get() *WorkspaceRemoteChange {
	return v.value
}

func (v *NullableWorkspaceRemoteChange) Set(val *WorkspaceRemoteChange) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceRemoteChange) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceRemoteChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceRemoteChange(val *WorkspaceRemoteChange) *NullableWorkspaceRemoteChange {
	return &NullableWorkspaceRemoteChange{value: val, isSet: true}
}

func (v NullableWorkspaceRemoteChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceRemoteChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


