/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SlackConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlackConnection{}

// SlackConnection struct for SlackConnection
type SlackConnection struct {
	Id string `json:"id"`
	Name string `json:"name"`
	TeamId string `json:"team_id"`
	BotUserId string `json:"bot_user_id"`
	EventsUrl string `json:"events_url"`
	CreatedAt time.Time `json:"created_at"`
}

type _SlackConnection SlackConnection

// NewSlackConnection instantiates a new SlackConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlackConnection(id string, name string, teamId string, botUserId string, eventsUrl string, createdAt time.Time) *SlackConnection {
	this := SlackConnection{}
	this.Id = id
	this.Name = name
	this.TeamId = teamId
	this.BotUserId = botUserId
	this.EventsUrl = eventsUrl
	this.CreatedAt = createdAt
	return &this
}

// NewSlackConnectionWithDefaults instantiates a new SlackConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlackConnectionWithDefaults() *SlackConnection {
	this := SlackConnection{}
	return &this
}

// GetId returns the Id field value
func (o *SlackConnection) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SlackConnection) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SlackConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SlackConnection) SetName(v string) {
	o.Name = v
}

// GetTeamId returns the TeamId field value
func (o *SlackConnection) GetTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *SlackConnection) SetTeamId(v string) {
	o.TeamId = v
}

// GetBotUserId returns the BotUserId field value
func (o *SlackConnection) GetBotUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BotUserId
}

// GetBotUserIdOk returns a tuple with the BotUserId field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetBotUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BotUserId, true
}

// SetBotUserId sets field value
func (o *SlackConnection) SetBotUserId(v string) {
	o.BotUserId = v
}

// GetEventsUrl returns the EventsUrl field value
func (o *SlackConnection) GetEventsUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventsUrl
}

// GetEventsUrlOk returns a tuple with the EventsUrl field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetEventsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventsUrl, true
}

// SetEventsUrl sets field value
func (o *SlackConnection) SetEventsUrl(v string) {
	o.EventsUrl = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SlackConnection) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SlackConnection) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SlackConnection) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SlackConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlackConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["team_id"] = o.TeamId
	toSerialize["bot_user_id"] = o.BotUserId
	toSerialize["events_url"] = o.EventsUrl
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *SlackConnection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"team_id",
		"bot_user_id",
		"events_url",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSlackConnection := _SlackConnection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSlackConnection)

	if err != nil {
		return err
	}

	*o = SlackConnection(varSlackConnection)

	return err
}

type NullableSlackConnection struct {
	value *SlackConnection
	isSet bool
}

func (v NullableSlackConnection) Get() *SlackConnection {
	return v.value
}

func (v *NullableSlackConnection) Set(val *SlackConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableSlackConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableSlackConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlackConnection(val *SlackConnection) *NullableSlackConnection {
	return &NullableSlackConnection{value: val, isSet: true}
}

func (v NullableSlackConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlackConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


