/*
Macrofold API

Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
)

// checks if the SyncWorktreeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncWorktreeRequest{}

// SyncWorktreeRequest struct for SyncWorktreeRequest
type SyncWorktreeRequest struct {
	Mode *string `json:"mode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SyncWorktreeRequest SyncWorktreeRequest

// NewSyncWorktreeRequest instantiates a new SyncWorktreeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncWorktreeRequest() *SyncWorktreeRequest {
	this := SyncWorktreeRequest{}
	var mode string = "push"
	this.Mode = &mode
	return &this
}

// NewSyncWorktreeRequestWithDefaults instantiates a new SyncWorktreeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncWorktreeRequestWithDefaults() *SyncWorktreeRequest {
	this := SyncWorktreeRequest{}
	var mode string = "push"
	this.Mode = &mode
	return &this
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *SyncWorktreeRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncWorktreeRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *SyncWorktreeRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *SyncWorktreeRequest) SetMode(v string) {
	o.Mode = &v
}

func (o SyncWorktreeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncWorktreeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyncWorktreeRequest) UnmarshalJSON(data []byte) (err error) {
	varSyncWorktreeRequest := _SyncWorktreeRequest{}

	err = json.Unmarshal(data, &varSyncWorktreeRequest)

	if err != nil {
		return err
	}

	*o = SyncWorktreeRequest(varSyncWorktreeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyncWorktreeRequest struct {
	value *SyncWorktreeRequest
	isSet bool
}

func (v NullableSyncWorktreeRequest) Get() *SyncWorktreeRequest {
	return v.value
}

func (v *NullableSyncWorktreeRequest) Set(val *SyncWorktreeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncWorktreeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncWorktreeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncWorktreeRequest(val *SyncWorktreeRequest) *NullableSyncWorktreeRequest {
	return &NullableSyncWorktreeRequest{value: val, isSet: true}
}

func (v NullableSyncWorktreeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncWorktreeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


