/*
Macrofold API

Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package macrofold

import (
	"encoding/json"
)

// checks if the ExecutionPolicyPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionPolicyPatch{}

// ExecutionPolicyPatch struct for ExecutionPolicyPatch
type ExecutionPolicyPatch struct {
	// Null restores plan default. An integer must not exceed the current plan limit.
	ConcurrencyLimit NullableInt32 `json:"concurrency_limit,omitempty"`
	// Null restores plan default. Changes affect new starts, never interrupt running work.
	MaxTimeoutSeconds NullableInt32 `json:"max_timeout_seconds,omitempty"`
}

// NewExecutionPolicyPatch instantiates a new ExecutionPolicyPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionPolicyPatch() *ExecutionPolicyPatch {
	this := ExecutionPolicyPatch{}
	return &this
}

// NewExecutionPolicyPatchWithDefaults instantiates a new ExecutionPolicyPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionPolicyPatchWithDefaults() *ExecutionPolicyPatch {
	this := ExecutionPolicyPatch{}
	return &this
}

// GetConcurrencyLimit returns the ConcurrencyLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecutionPolicyPatch) GetConcurrencyLimit() int32 {
	if o == nil || IsNil(o.ConcurrencyLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.ConcurrencyLimit.Get()
}

// GetConcurrencyLimitOk returns a tuple with the ConcurrencyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionPolicyPatch) GetConcurrencyLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConcurrencyLimit.Get(), o.ConcurrencyLimit.IsSet()
}

// HasConcurrencyLimit returns a boolean if a field has been set.
func (o *ExecutionPolicyPatch) HasConcurrencyLimit() bool {
	if o != nil && o.ConcurrencyLimit.IsSet() {
		return true
	}

	return false
}

// SetConcurrencyLimit gets a reference to the given NullableInt32 and assigns it to the ConcurrencyLimit field.
func (o *ExecutionPolicyPatch) SetConcurrencyLimit(v int32) {
	o.ConcurrencyLimit.Set(&v)
}
// SetConcurrencyLimitNil sets the value for ConcurrencyLimit to be an explicit nil
func (o *ExecutionPolicyPatch) SetConcurrencyLimitNil() {
	o.ConcurrencyLimit.Set(nil)
}

// UnsetConcurrencyLimit ensures that no value is present for ConcurrencyLimit, not even an explicit nil
func (o *ExecutionPolicyPatch) UnsetConcurrencyLimit() {
	o.ConcurrencyLimit.Unset()
}

// GetMaxTimeoutSeconds returns the MaxTimeoutSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecutionPolicyPatch) GetMaxTimeoutSeconds() int32 {
	if o == nil || IsNil(o.MaxTimeoutSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTimeoutSeconds.Get()
}

// GetMaxTimeoutSecondsOk returns a tuple with the MaxTimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionPolicyPatch) GetMaxTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTimeoutSeconds.Get(), o.MaxTimeoutSeconds.IsSet()
}

// HasMaxTimeoutSeconds returns a boolean if a field has been set.
func (o *ExecutionPolicyPatch) HasMaxTimeoutSeconds() bool {
	if o != nil && o.MaxTimeoutSeconds.IsSet() {
		return true
	}

	return false
}

// SetMaxTimeoutSeconds gets a reference to the given NullableInt32 and assigns it to the MaxTimeoutSeconds field.
func (o *ExecutionPolicyPatch) SetMaxTimeoutSeconds(v int32) {
	o.MaxTimeoutSeconds.Set(&v)
}
// SetMaxTimeoutSecondsNil sets the value for MaxTimeoutSeconds to be an explicit nil
func (o *ExecutionPolicyPatch) SetMaxTimeoutSecondsNil() {
	o.MaxTimeoutSeconds.Set(nil)
}

// UnsetMaxTimeoutSeconds ensures that no value is present for MaxTimeoutSeconds, not even an explicit nil
func (o *ExecutionPolicyPatch) UnsetMaxTimeoutSeconds() {
	o.MaxTimeoutSeconds.Unset()
}

func (o ExecutionPolicyPatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionPolicyPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ConcurrencyLimit.IsSet() {
		toSerialize["concurrency_limit"] = o.ConcurrencyLimit.Get()
	}
	if o.MaxTimeoutSeconds.IsSet() {
		toSerialize["max_timeout_seconds"] = o.MaxTimeoutSeconds.Get()
	}
	return toSerialize, nil
}

type NullableExecutionPolicyPatch struct {
	value *ExecutionPolicyPatch
	isSet bool
}

func (v NullableExecutionPolicyPatch) Get() *ExecutionPolicyPatch {
	return v.value
}

func (v *NullableExecutionPolicyPatch) Set(val *ExecutionPolicyPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionPolicyPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionPolicyPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionPolicyPatch(val *ExecutionPolicyPatch) *NullableExecutionPolicyPatch {
	return &NullableExecutionPolicyPatch{value: val, isSet: true}
}

func (v NullableExecutionPolicyPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionPolicyPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


