/*
 * Macrofold API
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.macrofold.api;

import dev.macrofold.ApiClient;
import dev.macrofold.ApiException;
import dev.macrofold.ApiResponse;
import dev.macrofold.Configuration;
import dev.macrofold.Pair;

import dev.macrofold.model.DeleteTrigger200Response;
import dev.macrofold.model.Error;
import dev.macrofold.model.ListTriggerDeliveries200Response;
import dev.macrofold.model.ListTriggers200Response;
import dev.macrofold.model.NewTrigger;
import dev.macrofold.model.Trigger;
import dev.macrofold.model.TriggerCreate;
import dev.macrofold.model.TriggerDelivery;
import dev.macrofold.model.TriggerPatch;
import dev.macrofold.model.TriggerSecret;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class TriggersApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public TriggersApi() {
    this(Configuration.getDefaultApiClient());
  }

  public TriggersApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a trigger or scheduled task
   * 
   * @param idempotencyKey  (required)
   * @param triggerCreate  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return NewTrigger
   * @throws ApiException if fails to make API call
   */
  public NewTrigger createTrigger(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull TriggerCreate triggerCreate, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return createTrigger(idempotencyKey, triggerCreate, xOrganizationId, null);
  }

  /**
   * Create a trigger or scheduled task
   * 
   * @param idempotencyKey  (required)
   * @param triggerCreate  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return NewTrigger
   * @throws ApiException if fails to make API call
   */
  public NewTrigger createTrigger(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull TriggerCreate triggerCreate, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<NewTrigger> localVarResponse = createTriggerWithHttpInfo(idempotencyKey, triggerCreate, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a trigger or scheduled task
   * 
   * @param idempotencyKey  (required)
   * @param triggerCreate  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;NewTrigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NewTrigger> createTriggerWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull TriggerCreate triggerCreate, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return createTriggerWithHttpInfo(idempotencyKey, triggerCreate, xOrganizationId, null);
  }

  /**
   * Create a trigger or scheduled task
   * 
   * @param idempotencyKey  (required)
   * @param triggerCreate  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;NewTrigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NewTrigger> createTriggerWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull TriggerCreate triggerCreate, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createTriggerRequestBuilder(idempotencyKey, triggerCreate, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createTrigger", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<NewTrigger>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        NewTrigger responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NewTrigger>() {});
        

        return new ApiResponse<NewTrigger>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createTriggerRequestBuilder(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull TriggerCreate triggerCreate, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'idempotencyKey' is set
    if (idempotencyKey == null) {
      throw new ApiException(400, "Missing the required parameter 'idempotencyKey' when calling createTrigger");
    }
    // verify the required parameter 'triggerCreate' is set
    if (triggerCreate == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerCreate' when calling createTrigger");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(triggerCreate);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a trigger; preserve accepted runs
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return DeleteTrigger200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteTrigger200Response deleteTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return deleteTrigger(triggerId, xOrganizationId, null);
  }

  /**
   * Delete a trigger; preserve accepted runs
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return DeleteTrigger200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteTrigger200Response deleteTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteTrigger200Response> localVarResponse = deleteTriggerWithHttpInfo(triggerId, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete a trigger; preserve accepted runs
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;DeleteTrigger200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteTrigger200Response> deleteTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return deleteTriggerWithHttpInfo(triggerId, xOrganizationId, null);
  }

  /**
   * Delete a trigger; preserve accepted runs
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteTrigger200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteTrigger200Response> deleteTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteTriggerRequestBuilder(triggerId, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteTrigger", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteTrigger200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteTrigger200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteTrigger200Response>() {});
        

        return new ApiResponse<DeleteTrigger200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteTriggerRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling deleteTrigger");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Inspect a trigger
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return Trigger
   * @throws ApiException if fails to make API call
   */
  public Trigger getTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return getTrigger(triggerId, xOrganizationId, null);
  }

  /**
   * Inspect a trigger
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return Trigger
   * @throws ApiException if fails to make API call
   */
  public Trigger getTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<Trigger> localVarResponse = getTriggerWithHttpInfo(triggerId, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Inspect a trigger
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;Trigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Trigger> getTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return getTriggerWithHttpInfo(triggerId, xOrganizationId, null);
  }

  /**
   * Inspect a trigger
   * 
   * @param triggerId  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Trigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Trigger> getTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTriggerRequestBuilder(triggerId, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTrigger", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Trigger>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Trigger responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Trigger>() {});
        

        return new ApiResponse<Trigger>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTriggerRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling getTrigger");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List trigger deliveries and linked runs
   * 
   * @param triggerId  (required)
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ListTriggerDeliveries200Response
   * @throws ApiException if fails to make API call
   */
  public ListTriggerDeliveries200Response listTriggerDeliveries(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return listTriggerDeliveries(triggerId, cursor, limit, xOrganizationId, null);
  }

  /**
   * List trigger deliveries and linked runs
   * 
   * @param triggerId  (required)
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ListTriggerDeliveries200Response
   * @throws ApiException if fails to make API call
   */
  public ListTriggerDeliveries200Response listTriggerDeliveries(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<ListTriggerDeliveries200Response> localVarResponse = listTriggerDeliveriesWithHttpInfo(triggerId, cursor, limit, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * List trigger deliveries and linked runs
   * 
   * @param triggerId  (required)
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;ListTriggerDeliveries200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListTriggerDeliveries200Response> listTriggerDeliveriesWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return listTriggerDeliveriesWithHttpInfo(triggerId, cursor, limit, xOrganizationId, null);
  }

  /**
   * List trigger deliveries and linked runs
   * 
   * @param triggerId  (required)
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListTriggerDeliveries200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListTriggerDeliveries200Response> listTriggerDeliveriesWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listTriggerDeliveriesRequestBuilder(triggerId, cursor, limit, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listTriggerDeliveries", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListTriggerDeliveries200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListTriggerDeliveries200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListTriggerDeliveries200Response>() {});
        

        return new ApiResponse<ListTriggerDeliveries200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listTriggerDeliveriesRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling listTriggerDeliveries");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}/deliveries"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List triggers and scheduled tasks
   * 
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param kind  (optional)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ListTriggers200Response
   * @throws ApiException if fails to make API call
   */
  public ListTriggers200Response listTriggers(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String kind, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return listTriggers(cursor, limit, kind, xOrganizationId, null);
  }

  /**
   * List triggers and scheduled tasks
   * 
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param kind  (optional)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ListTriggers200Response
   * @throws ApiException if fails to make API call
   */
  public ListTriggers200Response listTriggers(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String kind, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<ListTriggers200Response> localVarResponse = listTriggersWithHttpInfo(cursor, limit, kind, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * List triggers and scheduled tasks
   * 
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param kind  (optional)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;ListTriggers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListTriggers200Response> listTriggersWithHttpInfo(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String kind, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return listTriggersWithHttpInfo(cursor, limit, kind, xOrganizationId, null);
  }

  /**
   * List triggers and scheduled tasks
   * 
   * @param cursor  (optional)
   * @param limit  (optional, default to 25)
   * @param kind  (optional)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListTriggers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListTriggers200Response> listTriggersWithHttpInfo(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String kind, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listTriggersRequestBuilder(cursor, limit, kind, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listTriggers", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListTriggers200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListTriggers200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListTriggers200Response>() {});
        

        return new ApiResponse<ListTriggers200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listTriggersRequestBuilder(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String kind, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "kind";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("kind", kind));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retry a failed or uncertain Slack reply
   * Check Slack for an existing message before retrying an uncertain reply. This never reruns the agent.
   * @param triggerId  (required)
   * @param deliveryId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return TriggerDelivery
   * @throws ApiException if fails to make API call
   */
  public TriggerDelivery retryTriggerReply(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull UUID deliveryId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return retryTriggerReply(triggerId, deliveryId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Retry a failed or uncertain Slack reply
   * Check Slack for an existing message before retrying an uncertain reply. This never reruns the agent.
   * @param triggerId  (required)
   * @param deliveryId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return TriggerDelivery
   * @throws ApiException if fails to make API call
   */
  public TriggerDelivery retryTriggerReply(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull UUID deliveryId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<TriggerDelivery> localVarResponse = retryTriggerReplyWithHttpInfo(triggerId, deliveryId, idempotencyKey, body, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Retry a failed or uncertain Slack reply
   * Check Slack for an existing message before retrying an uncertain reply. This never reruns the agent.
   * @param triggerId  (required)
   * @param deliveryId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;TriggerDelivery&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerDelivery> retryTriggerReplyWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull UUID deliveryId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return retryTriggerReplyWithHttpInfo(triggerId, deliveryId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Retry a failed or uncertain Slack reply
   * Check Slack for an existing message before retrying an uncertain reply. This never reruns the agent.
   * @param triggerId  (required)
   * @param deliveryId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TriggerDelivery&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerDelivery> retryTriggerReplyWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull UUID deliveryId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = retryTriggerReplyRequestBuilder(triggerId, deliveryId, idempotencyKey, body, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("retryTriggerReply", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TriggerDelivery>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TriggerDelivery responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TriggerDelivery>() {});
        

        return new ApiResponse<TriggerDelivery>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder retryTriggerReplyRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull UUID deliveryId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling retryTriggerReply");
    }
    // verify the required parameter 'deliveryId' is set
    if (deliveryId == null) {
      throw new ApiException(400, "Missing the required parameter 'deliveryId' when calling retryTriggerReply");
    }
    // verify the required parameter 'idempotencyKey' is set
    if (idempotencyKey == null) {
      throw new ApiException(400, "Missing the required parameter 'idempotencyKey' when calling retryTriggerReply");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling retryTriggerReply");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}/deliveries/{delivery_id}/retry-reply"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()))
        .replace("{delivery_id}", ApiClient.urlEncode(deliveryId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rotate the incoming webhook secret
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return TriggerSecret
   * @throws ApiException if fails to make API call
   */
  public TriggerSecret rotateTriggerSecret(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return rotateTriggerSecret(triggerId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Rotate the incoming webhook secret
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return TriggerSecret
   * @throws ApiException if fails to make API call
   */
  public TriggerSecret rotateTriggerSecret(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<TriggerSecret> localVarResponse = rotateTriggerSecretWithHttpInfo(triggerId, idempotencyKey, body, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Rotate the incoming webhook secret
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;TriggerSecret&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerSecret> rotateTriggerSecretWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return rotateTriggerSecretWithHttpInfo(triggerId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Rotate the incoming webhook secret
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TriggerSecret&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerSecret> rotateTriggerSecretWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = rotateTriggerSecretRequestBuilder(triggerId, idempotencyKey, body, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("rotateTriggerSecret", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TriggerSecret>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TriggerSecret responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TriggerSecret>() {});
        

        return new ApiResponse<TriggerSecret>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder rotateTriggerSecretRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling rotateTriggerSecret");
    }
    // verify the required parameter 'idempotencyKey' is set
    if (idempotencyKey == null) {
      throw new ApiException(400, "Missing the required parameter 'idempotencyKey' when calling rotateTriggerSecret");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling rotateTriggerSecret");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}/rotate-secret"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Run a scheduled task now
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return TriggerDelivery
   * @throws ApiException if fails to make API call
   */
  public TriggerDelivery runTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return runTrigger(triggerId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Run a scheduled task now
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return TriggerDelivery
   * @throws ApiException if fails to make API call
   */
  public TriggerDelivery runTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<TriggerDelivery> localVarResponse = runTriggerWithHttpInfo(triggerId, idempotencyKey, body, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Run a scheduled task now
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;TriggerDelivery&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerDelivery> runTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return runTriggerWithHttpInfo(triggerId, idempotencyKey, body, xOrganizationId, null);
  }

  /**
   * Run a scheduled task now
   * 
   * @param triggerId  (required)
   * @param idempotencyKey  (required)
   * @param body  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TriggerDelivery&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TriggerDelivery> runTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = runTriggerRequestBuilder(triggerId, idempotencyKey, body, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("runTrigger", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TriggerDelivery>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TriggerDelivery responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TriggerDelivery>() {});
        

        return new ApiResponse<TriggerDelivery>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder runTriggerRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull Object body, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling runTrigger");
    }
    // verify the required parameter 'idempotencyKey' is set
    if (idempotencyKey == null) {
      throw new ApiException(400, "Missing the required parameter 'idempotencyKey' when calling runTrigger");
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling runTrigger");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}/run"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Edit or pause a trigger
   * Only the creator can edit/resume. Organization administrators can pause. Editing configuration invalidates deliveries that have not yet become runs.
   * @param triggerId  (required)
   * @param triggerPatch  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return Trigger
   * @throws ApiException if fails to make API call
   */
  public Trigger updateTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull TriggerPatch triggerPatch, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return updateTrigger(triggerId, triggerPatch, xOrganizationId, null);
  }

  /**
   * Edit or pause a trigger
   * Only the creator can edit/resume. Organization administrators can pause. Editing configuration invalidates deliveries that have not yet become runs.
   * @param triggerId  (required)
   * @param triggerPatch  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return Trigger
   * @throws ApiException if fails to make API call
   */
  public Trigger updateTrigger(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull TriggerPatch triggerPatch, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    ApiResponse<Trigger> localVarResponse = updateTriggerWithHttpInfo(triggerId, triggerPatch, xOrganizationId, headers);
    return localVarResponse.getData();
  }

  /**
   * Edit or pause a trigger
   * Only the creator can edit/resume. Organization administrators can pause. Editing configuration invalidates deliveries that have not yet become runs.
   * @param triggerId  (required)
   * @param triggerPatch  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @return ApiResponse&lt;Trigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Trigger> updateTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull TriggerPatch triggerPatch, @javax.annotation.Nullable UUID xOrganizationId) throws ApiException {
    return updateTriggerWithHttpInfo(triggerId, triggerPatch, xOrganizationId, null);
  }

  /**
   * Edit or pause a trigger
   * Only the creator can edit/resume. Organization administrators can pause. Editing configuration invalidates deliveries that have not yet become runs.
   * @param triggerId  (required)
   * @param triggerPatch  (required)
   * @param xOrganizationId Authorized membership selector for user tokens/sessions; cannot override API-key organization binding. Required when identity has multiple memberships and no selected grant context. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Trigger&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Trigger> updateTriggerWithHttpInfo(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull TriggerPatch triggerPatch, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateTriggerRequestBuilder(triggerId, triggerPatch, xOrganizationId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateTrigger", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Trigger>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Trigger responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Trigger>() {});
        

        return new ApiResponse<Trigger>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateTriggerRequestBuilder(@javax.annotation.Nonnull UUID triggerId, @javax.annotation.Nonnull TriggerPatch triggerPatch, @javax.annotation.Nullable UUID xOrganizationId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'triggerId' is set
    if (triggerId == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerId' when calling updateTrigger");
    }
    // verify the required parameter 'triggerPatch' is set
    if (triggerPatch == null) {
      throw new ApiException(400, "Missing the required parameter 'triggerPatch' when calling updateTrigger");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/triggers/{trigger_id}"
        .replace("{trigger_id}", ApiClient.urlEncode(triggerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xOrganizationId != null) {
      localVarRequestBuilder.header("X-Organization-Id", xOrganizationId.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(triggerPatch);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
