/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "harness")]
    pub harness: Harness,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    #[serde(rename = "billing_mode")]
    pub billing_mode: BillingMode,
    #[serde(rename = "provider_connection_id", skip_serializing_if = "Option::is_none")]
    pub provider_connection_id: Option<uuid::Uuid>,
    #[serde(rename = "connection_grants", skip_serializing_if = "Option::is_none")]
    pub connection_grants: Option<Vec<models::Grant>>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::Limits>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Agent {
    pub fn new(name: String, harness: Harness, model: String, billing_mode: BillingMode, id: uuid::Uuid, organization_id: uuid::Uuid, version: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> Agent {
        Agent {
            name,
            harness,
            model,
            instructions: None,
            billing_mode,
            provider_connection_id: None,
            connection_grants: None,
            limits: None,
            id,
            organization_id,
            version,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Harness {
    #[serde(rename = "codex")]
    Codex,
    #[serde(rename = "claude-code")]
    ClaudeCode,
    #[serde(rename = "opencode")]
    Opencode,
}

impl Default for Harness {
    fn default() -> Harness {
        Self::Codex
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingMode {
    #[serde(rename = "byok")]
    Byok,
    #[serde(rename = "managed")]
    Managed,
}

impl Default for BillingMode {
    fn default() -> BillingMode {
        Self::Byok
    }
}

