/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionAccess {
    #[serde(rename = "connection_id")]
    pub connection_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "organization_wide")]
    pub organization_wide: bool,
    #[serde(rename = "tools")]
    pub tools: Vec<String>,
    #[serde(rename = "rule_count")]
    pub rule_count: i32,
    #[serde(rename = "can_grant")]
    pub can_grant: bool,
    #[serde(rename = "can_revoke")]
    pub can_revoke: bool,
}

impl ConnectionAccess {
    pub fn new(connection_id: uuid::Uuid, version: String, organization_wide: bool, tools: Vec<String>, rule_count: i32, can_grant: bool, can_revoke: bool) -> ConnectionAccess {
        ConnectionAccess {
            connection_id,
            version,
            organization_wide,
            tools,
            rule_count,
            can_grant,
            can_revoke,
        }
    }
}

