/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorCatalogEntry {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "logo")]
    pub logo: String,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    #[serde(rename = "tool_count")]
    pub tool_count: i32,
    /// Operator auth config, version pin and callback verification are configured. This is not proof of user authorization or successful live execution.
    #[serde(rename = "connectable")]
    pub connectable: bool,
}

impl ConnectorCatalogEntry {
    pub fn new(slug: String, name: String, description: String, logo: String, categories: Vec<String>, tool_count: i32, connectable: bool) -> ConnectorCatalogEntry {
        ConnectorCatalogEntry {
            slug,
            name,
            description,
            logo,
            categories,
            tool_count,
            connectable,
        }
    }
}

