/*
 * Macrofold API
 *
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionBinding {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "billing_mode")]
    pub billing_mode: BillingMode,
    #[serde(rename = "provider_connection_id", skip_serializing_if = "Option::is_none")]
    pub provider_connection_id: Option<uuid::Uuid>,
}

impl DecisionBinding {
    pub fn new(provider: Provider, model: String, billing_mode: BillingMode) -> DecisionBinding {
        DecisionBinding {
            provider,
            model,
            billing_mode,
            provider_connection_id: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "anthropic")]
    Anthropic,
    #[serde(rename = "typesafe")]
    Typesafe,
    #[serde(rename = "openrouter")]
    Openrouter,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Anthropic
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingMode {
    #[serde(rename = "managed")]
    Managed,
    #[serde(rename = "byok")]
    Byok,
}

impl Default for BillingMode {
    fn default() -> BillingMode {
        Self::Managed
    }
}

