/*
 * Macrofold API
 *
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionQuestionOneOf1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "criteria")]
    pub criteria: std::collections::HashMap<String, String>,
}

impl DecisionQuestionOneOf1 {
    pub fn new(kind: Kind, criteria: std::collections::HashMap<String, String>) -> DecisionQuestionOneOf1 {
        DecisionQuestionOneOf1 {
            kind,
            criteria,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "choice")]
    Choice,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Choice
    }
}

