/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubRepositories {
    #[serde(rename = "data")]
    pub data: Vec<models::GithubRepositoriesDataInner>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

impl GithubRepositories {
    pub fn new(data: Vec<models::GithubRepositoriesDataInner>, truncated: bool) -> GithubRepositories {
        GithubRepositories {
            data,
            truncated,
        }
    }
}

