/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSlackConnectionChannels200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::SlackChannel>,
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl ListSlackConnectionChannels200Response {
    pub fn new(data: Vec<models::SlackChannel>, next_cursor: Option<String>) -> ListSlackConnectionChannels200Response {
        ListSlackConnectionChannels200Response {
            data,
            next_cursor,
        }
    }
}

