/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    #[serde(rename = "definition_version")]
    pub definition_version: String,
    #[serde(rename = "from")]
    pub from: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "to")]
    pub to: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "timezone")]
    pub timezone: Timezone,
    #[serde(rename = "observed_at")]
    pub observed_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "complete_through", skip_serializing_if = "Option::is_none")]
    pub complete_through: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "missing_sources")]
    pub missing_sources: Vec<String>,
    /// Versioned metadata; secrets and unbounded arbitrary payloads are prohibited.
    #[serde(rename = "filters")]
    pub filters: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "metrics")]
    pub metrics: Vec<models::Metric>,
    #[serde(rename = "evidence_urls", skip_serializing_if = "Option::is_none")]
    pub evidence_urls: Option<Vec<String>>,
    #[serde(rename = "recommendations", skip_serializing_if = "Option::is_none")]
    pub recommendations: Option<Vec<models::Recommendation>>,
    #[serde(rename = "scheduling", skip_serializing_if = "Option::is_none")]
    pub scheduling: Option<Box<models::SchedulingReport>>,
}

impl Report {
    pub fn new(definition_version: String, from: chrono::DateTime<chrono::FixedOffset>, to: chrono::DateTime<chrono::FixedOffset>, timezone: Timezone, observed_at: chrono::DateTime<chrono::FixedOffset>, missing_sources: Vec<String>, filters: std::collections::HashMap<String, serde_json::Value>, metrics: Vec<models::Metric>) -> Report {
        Report {
            definition_version,
            from,
            to,
            timezone,
            observed_at,
            complete_through: None,
            missing_sources,
            filters,
            metrics,
            evidence_urls: None,
            recommendations: None,
            scheduling: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Timezone {
    #[serde(rename = "UTC")]
    Utc,
}

impl Default for Timezone {
    fn default() -> Timezone {
        Self::Utc
    }
}

