/*
 * Macrofold API
 *
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sandbox {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
    #[serde(rename = "worktree_id")]
    pub worktree_id: uuid::Uuid,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "long_running")]
    pub long_running: bool,
    /// Seconds to retain idle compute after a run. 0 or null on a run releases compute. Omitted inherits the sandbox policy.
    #[serde(rename = "keep_warm_seconds", deserialize_with = "Option::deserialize")]
    pub keep_warm_seconds: Option<i32>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "active_run_id", deserialize_with = "Option::deserialize")]
    pub active_run_id: Option<uuid::Uuid>,
    #[serde(rename = "idle_expires_at", deserialize_with = "Option::deserialize")]
    pub idle_expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "cost_micro_usd")]
    pub cost_micro_usd: String,
    #[serde(rename = "max_cost_micro_usd")]
    pub max_cost_micro_usd: String,
    #[serde(rename = "reserved_micro_usd")]
    pub reserved_micro_usd: String,
    #[serde(rename = "rate_micro_usd_per_minute")]
    pub rate_micro_usd_per_minute: String,
    #[serde(rename = "failure_code", deserialize_with = "Option::deserialize")]
    pub failure_code: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Sandbox {
    pub fn new(id: uuid::Uuid, workspace_id: uuid::Uuid, worktree_id: uuid::Uuid, name: Option<String>, long_running: bool, keep_warm_seconds: Option<i32>, status: Status, active_run_id: Option<uuid::Uuid>, idle_expires_at: Option<chrono::DateTime<chrono::FixedOffset>>, cost_micro_usd: String, max_cost_micro_usd: String, reserved_micro_usd: String, rate_micro_usd_per_minute: String, failure_code: Option<String>, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Sandbox {
        Sandbox {
            id,
            workspace_id,
            worktree_id,
            name,
            long_running,
            keep_warm_seconds,
            status,
            active_run_id,
            idle_expires_at,
            cost_micro_usd,
            max_cost_micro_usd,
            reserved_micro_usd,
            rate_micro_usd_per_minute,
            failure_code,
            created_at,
            updated_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "creating")]
    Creating,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "pausing")]
    Pausing,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "destroying")]
    Destroying,
    #[serde(rename = "destroyed")]
    Destroyed,
    #[serde(rename = "error")]
    Error,
}

impl Default for Status {
    fn default() -> Status {
        Self::Creating
    }
}

