/*
 * Macrofold API
 *
 * Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorktreeOptionsBranchesInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ref")]
    pub r#ref: String,
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
}

impl WorktreeOptionsBranchesInner {
    pub fn new(name: String, r#ref: String, workspace_id: uuid::Uuid) -> WorktreeOptionsBranchesInner {
        WorktreeOptionsBranchesInner {
            name,
            r#ref,
            workspace_id,
        }
    }
}

