/*
 * Macrofold API
 *
 * Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorktreeSourceOneOf {
    #[serde(rename = "kind", deserialize_with = "Option::deserialize")]
    pub kind: Option<serde_json::Value>,
    #[serde(rename = "ref")]
    pub r#ref: String,
}

impl WorktreeSourceOneOf {
    pub fn new(kind: Option<serde_json::Value>, r#ref: String) -> WorktreeSourceOneOf {
        WorktreeSourceOneOf {
            kind,
            r#ref,
        }
    }
}

