/** Presentation choices only; every study uses the same public API and project model. */
export const studyBrand = 'Macrofold';
export const headline = 'Stand on the Shoulders of Giants.';
export const subtitle =
  'Use an entire agent harness as one unit of execution. Invoke it through API, CLI, or the dashboard. The power of Claude Code, Codex, and Opencode - in your product.';

export const homepages = [
  {
    slug: 'foundation',
    name: 'Foundation',
    hero: 'split',
    story: 'scroll',
    diagram: 'branches',
    description: 'A quiet split hero. One evolving project diagram follows the five chapters.',
    introduction: 'Everything you like about local agents. Available to your product.',
    references: 'Resend · Neon · LiveKit',
    accent: 'ice',
  },
  {
    slug: 'immersion',
    name: 'Immersion',
    hero: 'cinematic',
    story: 'scroll',
    diagram: 'layers',
    description: 'A full-bleed particle field and a luminous, layered workspace narrative.',
    introduction: 'A small request. A much bigger working environment.',
    references: 'Inngest · Modal · Exa',
    accent: 'violet',
  },
  {
    slug: 'precision',
    name: 'Precision',
    hero: 'framed',
    story: 'tabs',
    diagram: 'circuit',
    description: 'An instrument-like frame, compact code, and a selectable architecture diagram.',
    introduction: 'A clear path from a prompt to persistent work.',
    references: 'Unkey · Firecrawl · Vercel',
    accent: 'ice',
  },
  {
    slug: 'chapters',
    name: 'Chapters',
    hero: 'editorial',
    story: 'chapters',
    diagram: 'branches',
    description: 'Large editorial type. Five illustrated chapters, with room to read each one.',
    introduction: 'From the directory you know to the system you can build.',
    references: 'Stripe · Anthropic · E2B',
    accent: 'pearl',
  },
  {
    slug: 'workbench',
    name: 'Workbench',
    hero: 'compact',
    story: 'tabs',
    diagram: 'terminal',
    description: 'A tight developer opening and a familiar file-and-terminal feature explorer.',
    introduction: 'The familiar workflow, with a cloud address.',
    references: 'Daytona · OpenCode · OpenClaw',
    accent: 'green',
  },
  {
    slug: 'panorama',
    name: 'Panorama',
    hero: 'panoramic',
    story: 'scroll',
    diagram: 'lanes',
    description: 'A broad Swarm horizon. Parallel lanes connect working folders to saved versions.',
    introduction: 'Give every task its own place to work.',
    references: 'Modal · Neon · Ably',
    accent: 'ice',
  },
  {
    slug: 'atlas',
    name: 'Atlas',
    hero: 'asymmetric',
    story: 'chapters',
    diagram: 'layers',
    description:
      'Offset composition and alternating dimensional diagrams, presented as a field of capabilities.',
    introduction: 'Your project is the starting point. Keep building from there.',
    references: 'Exa · Supabase · Pinecone',
    accent: 'violet',
  },
  {
    slug: 'relay',
    name: 'Relay',
    hero: 'split',
    story: 'tabs',
    diagram: 'lanes',
    description: 'A product-focused split hero and a routing view you can explore by interface.',
    introduction: 'One project. As many ways in as your product needs.',
    references: 'Composio · Merge · LiveKit',
    accent: 'green',
  },
  {
    slug: 'sequence',
    name: 'Sequence',
    hero: 'editorial',
    story: 'rail',
    diagram: 'circuit',
    description: 'A typographic opening and a deliberate, step-by-step product presentation.',
    introduction: 'Follow one project from its first file to its next task.',
    references: 'Firecrawl · Inngest · Replicate',
    accent: 'pearl',
  },
  {
    slug: 'synthesis',
    name: 'Synthesis',
    hero: 'cinematic',
    story: 'scroll',
    diagram: 'terminal',
    description: 'The expansive Swarm hero gives way to a precise, scroll-linked developer workspace.',
    introduction: 'The complete working context, behind one API.',
    references: 'Resend · WorkOS · OpenAI',
    accent: 'ice',
  },
] as const;
export type Homepage = (typeof homepages)[number];
export type DiagramStyle = Homepage['diagram'];

export const stages = [
  {
    id: 'project',
    label: 'Project',
    title: 'Start with a directory. Just like you do locally.',
    body: 'Source code, instructions, notes, and artifacts live together in a project. Give the agent a real working folder, with the files it needs to make progress.',
    detail: 'A project groups your hosted workspaces.',
    local: 'Your local project directory',
    cloud: 'A project your application can address',
    link: '/docs/workspaces',
  },
  {
    id: 'worktrees',
    label: 'Worktrees',
    title: 'Let independent tasks work side by side.',
    body: 'Fan the project out into separate worktrees. Put Codex on one task, Claude Code on another, and OpenCode on a third. Each works in its own sandbox and branch.',
    detail:
      'One active writer per workspace. Parallel work uses independent workspaces, within your account limits.',
    local: 'Separate branches and working folders',
    cloud: 'Independent agent executions',
    link: '/docs/workspaces',
  },
  {
    id: 'versions',
    label: 'Persistence & Git',
    title: 'The run ends. The work stays.',
    body: 'Return to saved files for the next task. Inspect checkpoints and restore a revision. Connect GitHub to synchronize the work with your repository.',
    detail:
      'Verified checkpoints preserve files. GitHub sync is optional; conflicts stay visible and never force a push.',
    local: 'Files on disk and Git history',
    cloud: 'Persistent workspaces and optional GitHub sync',
    link: '/docs/workspaces',
  },
  {
    id: 'interfaces',
    label: 'API, CLI & UI',
    title: 'The same project, wherever you work.',
    body: 'Start from your application. Check in from your terminal. Review files, output, and run history in the dashboard. All three interfaces address the same hosted work.',
    detail: 'Linking the CLI selects remote context; it does not silently upload your local files.',
    local: 'A terminal open beside your editor',
    cloud: 'API, CLI, and dashboard access',
    link: '/docs/cli',
  },
  {
    id: 'routing',
    label: 'In your product',
    title: 'Put each agent exactly where it is useful.',
    body: 'Let a backend request target one workspace and a CLI command target another. Inspect either from the UI. Stream progress, collect the result, and send the next task.',
    detail:
      'Requests choose an authorized project, workspace, or session. Interfaces do not bypass workspace serialization.',
    local: 'You choose which agent to talk to',
    cloud: 'Your product can make that choice too',
    link: '/docs/api/quickstart',
  },
] as const;
