# coding: utf-8

"""
    Macrofold API

    Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReasoningEventData(BaseModel):
    """
    Native reasoning.started/delta/completed payload. Provider-exposed readable reasoning only; separate from output.delta and final output_text. Append delta text by reasoning_id in event sequence order. Completion closes a block, not the run. A terminal run without block completion means interruption.
    """ # noqa: E501
    reasoning_id: StrictStr = Field(description="Stable block identity within this run; distinct across model turns.")
    format: Optional[StrictStr] = Field(default=None, description="Provider summary or provider-exposed thinking text; included on started/delta.")
    text: Optional[StrictStr] = Field(default=None, description="Append-only readable fragment on reasoning.delta. Never encrypted reasoning or a signature.")
    status: Optional[StrictStr] = Field(default=None, description="On reasoning.completed; completed means the block ended, not that its statements are authoritative.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["reasoning_id", "format", "text", "status"]

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['summary', 'text']):
            raise ValueError("must be one of enum values ('summary', 'text')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['completed', 'interrupted']):
            raise ValueError("must be one of enum values ('completed', 'interrupted')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReasoningEventData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReasoningEventData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reasoning_id": obj.get("reasoning_id"),
            "format": obj.get("format"),
            "text": obj.get("text"),
            "status": obj.get("status")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


