# coding: utf-8

"""
    Macrofold API

    Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from macrofold.models.run_accepted_urls import RunAcceptedUrls
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RunAccepted(BaseModel):
    """
    RunAccepted
    """ # noqa: E501
    run_id: UUID
    session_id: Optional[UUID]
    worktree_id: Optional[UUID]
    status: StrictStr
    urls: RunAcceptedUrls
    queue_expires_at: Optional[datetime] = None
    wait_seconds: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Submission to execution start, or elapsed wait through now/completion if never started.")
    waiting_reason: Optional[StrictStr] = Field(default=None, description="Snapshot, not a queue position or start-time estimate. Null when no longer queued.")
    reserved_micro_usd: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Funds still held and unavailable for other jobs; released on settlement.")
    scheduling_class: Optional[StrictStr] = None
    kind: Optional[StrictStr] = None
    worker_id: Optional[UUID] = Field(default=None, description="Explicit reusable compute target, independent of the Run context.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["run_id", "session_id", "worktree_id", "status", "urls", "queue_expires_at", "wait_seconds", "waiting_reason", "reserved_micro_usd", "scheduling_class", "kind", "worker_id"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'provisioning', 'running']):
            raise ValueError("must be one of enum values ('queued', 'provisioning', 'running')")
        return value

    @field_validator('waiting_reason')
    def waiting_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['global_capacity', 'account_concurrency', 'earlier_worktree_work', 'scheduler_turn', 'cancellation_requested', 'deadline_expired', 'worktree_unavailable', 'lightweight_capacity', 'reserved_lightweight_capacity', 'worker_paused', 'worker_destroyed', 'worker_expired', 'worker_concurrency', 'worker_cost_limit', 'worker_instance_limit', 'worker_starting', 'worker_capacity', 'worker_lifetime', 'compute_unavailable', 'insufficient_credits']):
            raise ValueError("must be one of enum values ('global_capacity', 'account_concurrency', 'earlier_worktree_work', 'scheduler_turn', 'cancellation_requested', 'deadline_expired', 'worktree_unavailable', 'lightweight_capacity', 'reserved_lightweight_capacity', 'worker_paused', 'worker_destroyed', 'worker_expired', 'worker_concurrency', 'worker_cost_limit', 'worker_instance_limit', 'worker_starting', 'worker_capacity', 'worker_lifetime', 'compute_unavailable', 'insufficient_credits')")
        return value

    @field_validator('reserved_micro_usd', mode="before")
    def reserved_micro_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]+$/")
        return value

    @field_validator('scheduling_class')
    def scheduling_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['background', 'interactive']):
            raise ValueError("must be one of enum values ('background', 'interactive')")
        return value

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['native_agent', 'inference', 'bounded_agent']):
            raise ValueError("must be one of enum values ('native_agent', 'inference', 'bounded_agent')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunAccepted from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of urls
        if self.urls:
            _dict['urls'] = self.urls.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['session_id'] = None

        # set to None if worktree_id (nullable) is None
        # and model_fields_set contains the field
        if self.worktree_id is None and "worktree_id" in self.model_fields_set:
            _dict['worktree_id'] = None

        # set to None if waiting_reason (nullable) is None
        # and model_fields_set contains the field
        if self.waiting_reason is None and "waiting_reason" in self.model_fields_set:
            _dict['waiting_reason'] = None

        # set to None if worker_id (nullable) is None
        # and model_fields_set contains the field
        if self.worker_id is None and "worker_id" in self.model_fields_set:
            _dict['worker_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunAccepted from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "run_id": obj.get("run_id"),
            "session_id": obj.get("session_id"),
            "worktree_id": obj.get("worktree_id"),
            "status": obj.get("status"),
            "urls": RunAcceptedUrls.from_dict(obj["urls"]) if obj.get("urls") is not None else None,
            "queue_expires_at": obj.get("queue_expires_at"),
            "wait_seconds": obj.get("wait_seconds"),
            "waiting_reason": obj.get("waiting_reason"),
            "reserved_micro_usd": obj.get("reserved_micro_usd"),
            "scheduling_class": obj.get("scheduling_class"),
            "kind": obj.get("kind"),
            "worker_id": obj.get("worker_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


