# coding: utf-8

"""
    Macrofold API

    Manage persistent projects, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from macrofold.models.grant import Grant
from macrofold.models.limits import Limits
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RunCreate(BaseModel):
    """
    Exactly one project/workspace/session selector. A new session requires an agent preset or explicit harness and model. BYOK requires a compatible provider connection. Session harness is immutable. Runtime validates these ownership/catalog-dependent rules.
    """ # noqa: E501
    prompt: Annotated[str, Field(min_length=1, strict=True, max_length=100000)]
    project_id: Optional[UUID] = None
    workspace_id: Optional[UUID] = None
    session_id: Optional[UUID] = None
    agent_id: Optional[UUID] = None
    harness: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    billing_mode: Optional[StrictStr] = None
    provider_connection_id: Optional[UUID] = None
    connection_grants: Optional[List[Grant]] = None
    limits: Optional[Limits] = None
    webhook_endpoint_ids: Optional[List[UUID]] = None
    queue_timeout_seconds: Optional[Annotated[int, Field(le=86400, strict=True, ge=1)]] = Field(default=None, description="Maximum wait before execution starts, measured from submission. Shorten per request; never extends execution or retention.")
    scheduling_class: Optional[StrictStr] = Field(default=None, description="Interactive work receives first consideration at a free slot; no preemption or immediate-capacity guarantee.")
    queue_if_busy: Optional[StrictBool] = Field(default=None, description="Only session follow-ups can queue behind workspace work.")
    __properties: ClassVar[List[str]] = ["prompt", "project_id", "workspace_id", "session_id", "agent_id", "harness", "model", "billing_mode", "provider_connection_id", "connection_grants", "limits", "webhook_endpoint_ids", "queue_timeout_seconds", "scheduling_class", "queue_if_busy"]

    @field_validator('harness')
    def harness_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['codex', 'claude-code', 'opencode']):
            raise ValueError("must be one of enum values ('codex', 'claude-code', 'opencode')")
        return value

    @field_validator('billing_mode')
    def billing_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['byok', 'managed']):
            raise ValueError("must be one of enum values ('byok', 'managed')")
        return value

    @field_validator('scheduling_class')
    def scheduling_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['background', 'interactive']):
            raise ValueError("must be one of enum values ('background', 'interactive')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in connection_grants (list)
        _items = []
        if self.connection_grants:
            for _item_connection_grants in self.connection_grants:
                if _item_connection_grants:
                    _items.append(_item_connection_grants.to_dict())
            _dict['connection_grants'] = _items
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prompt": obj.get("prompt"),
            "project_id": obj.get("project_id"),
            "workspace_id": obj.get("workspace_id"),
            "session_id": obj.get("session_id"),
            "agent_id": obj.get("agent_id"),
            "harness": obj.get("harness"),
            "model": obj.get("model"),
            "billing_mode": obj.get("billing_mode"),
            "provider_connection_id": obj.get("provider_connection_id"),
            "connection_grants": [Grant.from_dict(_item) for _item in obj["connection_grants"]] if obj.get("connection_grants") is not None else None,
            "limits": Limits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "webhook_endpoint_ids": obj.get("webhook_endpoint_ids"),
            "queue_timeout_seconds": obj.get("queue_timeout_seconds"),
            "scheduling_class": obj.get("scheduling_class"),
            "queue_if_busy": obj.get("queue_if_busy")
        })
        return _obj


