# coding: utf-8

"""
    Macrofold API

    Manage persistent workspaces, run cloud agents, stream progress, and integrate tools, billing, and operator reporting. Provider-owned OAuth, internal runtime ingress, and MCP JSON-RPC use separate contracts.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from macrofold.models.agent_permissions import AgentPermissions
from macrofold.models.worktree_source import WorktreeSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorktreeCreate(BaseModel):
    """
    Create an independent worktree addressed by ID. Name alone creates its derived branch; branch alone supplies the name. Both omitted defers name and branch until the first accepted agent run. Names are unique in the workspace. Source selects saved starting files and never uploads a local folder.
    """ # noqa: E501
    name: Optional[Annotated[str, Field(strict=True, max_length=151)]] = Field(default=None, description="Optional. Leave empty for smart naming.")
    checkpoint_id: Optional[UUID] = None
    branch: Optional[Annotated[str, Field(strict=True, max_length=151)]] = Field(default=None, description="Optional. Leave empty for smart naming.")
    source: Optional[WorktreeSource] = None
    branch_mode: Optional[StrictStr] = Field(default=None, description="Auto uses a named existing branch or creates a new branch; new rejects an existing branch; existing requires a saved branch.")
    permissions: Optional[AgentPermissions] = None
    __properties: ClassVar[List[str]] = ["name", "checkpoint_id", "branch", "source", "branch_mode", "permissions"]

    @field_validator('branch_mode')
    def branch_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'new', 'existing']):
            raise ValueError("must be one of enum values ('auto', 'new', 'existing')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorktreeCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of permissions
        if self.permissions:
            _dict['permissions'] = self.permissions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorktreeCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "checkpoint_id": obj.get("checkpoint_id"),
            "branch": obj.get("branch"),
            "source": WorktreeSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "branch_mode": obj.get("branch_mode"),
            "permissions": AgentPermissions.from_dict(obj["permissions"]) if obj.get("permissions") is not None else None
        })
        return _obj


